In [2]:
!pip3 install openai==0.28

Defaulting to user installation because normal site-packages is not writeable
Collecting openai==0.28
  Downloading openai-0.28.0-py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 3.1 MB/s eta 0:00:01
Collecting tqdm
  Downloading tqdm-4.67.0-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 8.3 MB/s  eta 0:00:01
Collecting requests>=2.20
  Downloading requests-2.32.3-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 12.0 MB/s eta 0:00:01
Collecting aiohttp
  Downloading aiohttp-3.10.10-cp39-cp39-macosx_11_0_arm64.whl (391 kB)
     |████████████████████████████████| 391 kB 12.3 MB/s eta 0:00:01
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 10.2 MB/s eta 0:00:01
Collecting certifi>=2017.4.17
  Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
     |████████████████████████████████| 167 kB 20.7 MB/s eta 0:00:01
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.4.0-cp39-cp39-macosx_11_0_arm64.whl (120 kB)
     |████████████████████████████████| 120 kB 35.5 MB/s eta 0:00:01
Collecting idna<4,>=2.5
  Downloading idna-3.10-py3-none-any.whl (70 kB)
     |████████████████████████████████| 70 kB 18.6 MB/s eta 0:00:01
Collecting attrs>=17.3.0
  Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 7.3 MB/s  eta 0:00:01
Collecting yarl<2.0,>=1.12.0
  Downloading yarl-1.17.1-cp39-cp39-macosx_11_0_arm64.whl (91 kB)
     |████████████████████████████████| 91 kB 20.5 MB/s eta 0:00:01
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout<5.0,>=4.0
  Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting aiohappyeyeballs>=2.3.0
  Downloading aiohappyeyeballs-2.4.3-py3-none-any.whl (14 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.1.0-cp39-cp39-macosx_11_0_arm64.whl (29 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.5.0-cp39-cp39-macosx_11_0_arm64.whl (52 kB)
     |████████████████████████████████| 52 kB 6.4 MB/s  eta 0:00:01
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/u1469481/Library/Python/3.9/lib/python/site-packages (from multidict<7.0,>=4.5->aiohttp->openai==0.28) (4.12.2)
Collecting propcache>=0.2.0
  Downloading propcache-0.2.0-cp39-cp39-macosx_11_0_arm64.whl (46 kB)
     |████████████████████████████████| 46 kB 12.8 MB/s eta 0:00:01
Installing collected packages: propcache, multidict, idna, frozenlist, yarl, urllib3, charset-normalizer, certifi, attrs, async-timeout, aiosignal, aiohappyeyeballs, tqdm, requests, aiohttp, openai
Successfully installed aiohappyeyeballs-2.4.3 aiohttp-3.10.10 aiosignal-1.3.1 async-timeout-4.0.3 attrs-24.2.0 certifi-2024.8.30 charset-normalizer-3.4.0 frozenlist-1.5.0 idna-3.10 multidict-6.1.0 openai-0.28.0 propcache-0.2.0 requests-2.32.3 tqdm-4.67.0 urllib3-2.2.3 yarl-1.17.1
WARNING: You are using pip version 21.2.4; however, version 24.3.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [3]:
import openai

/Users/u1469481/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [4]:
openai.api_key = 'sk-proj-zvfr2IvWfqEUqsnmwIBJT3BlbkFJMxh6YiSgfcG6vEcMGJ35'

### Semantic sort using single column

In [ ]:
def semantic_cort_column(column_name, values, mod="3.5-turbo"):
  prompt = f"Sort the values {values} based on their semantic meaning for the column '{column_name}. Try to avoid alphabetical sorting and use context and semantic relationships. Provide the values and explain the sorting criteria. Give 5 different ways to sort these values, each with its own explanation."


  # response = openai.ChatCompletion.create(
  # engine="gpt-3.5-turbo",
  # prompt=prompt,
#)
  response = openai.ChatCompletion.create(
        model=f"gpt-{mod}",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=1000,
        n=1,
        stop=None,
        temperature=0.7
    )

  return response.choices[0].message['content']

In [ ]:
res = semantic_cort_column('job level', 'junior, senior, associate')

In [ ]:
final = res.split('\n\n')

In [ ]:
for suggestion in final:
  print(suggestion)
  print()

Here are five different ways to sort the values junior, senior, associate based on their semantic meaning for the column 'job level':

1. **Hierarchy Sorting**:
   - Senior
   - Associate
   - Junior
   Explanation: This sorting reflects a typical hierarchical structure where seniority implies higher authority or experience, followed by associates and then juniors.

2. **Experience Level Sorting**:
   - Junior
   - Associate
   - Senior
   Explanation: This sorting considers the level of experience and expertise, where juniors are at the entry-level, followed by associates with some experience, and seniors with the most experience.

3. **Responsibility Sorting**:
   - Junior
   - Senior
   - Associate
   Explanation: Here, the sorting is based on the level of responsibility associated with each job level, with juniors having the least responsibility, followed by associates, and then seniors with the highest level of responsibility.

4. **Promotion Path Sorting**:
   - Associate
   - Junior
   - Senior
   Explanation: This sorting represents a typical promotion path within an organization, where employees start as associates, then progress to juniors, and finally reach the senior level.

5. **Skill Level Sorting**:
   - Junior
   - Associate
   - Senior
   Explanation: This sorting is based on the assumption that juniors possess basic skills, associates have intermediate skills, and seniors have advanced skills and expertise in their respective roles.

In [ ]:
mood = semantic_cort_column('mood', 'content, elated, depressed')

In [ ]:
mood

"Sorting the values content, elated, and depressed based on their semantic meaning for the column 'mood' involves arranging them in a particular order that reflects their emotional connotations. Here are 5 different ways to sort these values, along with their explanations:\n\n1. Ascending order based on positivity:\n- Sorted values: depressed, content, elated\n- Explanation: This sorting criteria arranges the values from the most negative emotion (depressed) to the most positive emotion (elated).\n\n2. Descending order based on positivity:\n- Sorted values: elated, content, depressed\n- Explanation: In this sorting, the values are arranged from the most positive emotion (elated) to the most negative emotion (depressed).\n\n3. Alphabetical order:\n- Sorted values: content, depressed, elated\n- Explanation: This sorting criteria arranges the values in alphabetical order based on their spellings.\n\n4. Reversed alphabetical order:\n- Sorted values: elated, depressed, content\n- Explanation: In this sorting, the values are arranged in reverse alphabetical order based on their spellings.\n\n5. Random order based on emotional intensity:\n- Sorted values: content, depressed, elated\n- Explanation: This sorting criteria considers emotional intensity, placing the neutral emotion (content) first, followed by the negative emotion (depressed), and then the positive emotion (elated).\n\nThese different ways of sorting the values content, elated, and depressed provide insights into how the values can be arranged based on their emotional connotations, positivity, alphabetical order, or emotional intensity."

In [ ]:
final_mood = mood.split('\n\n')

In [ ]:
for suggestion in final_mood:
  print(suggestion)
  print()
  print()

Sure! Here are five different ways to sort the values content, elated, and depressed based on their semantic meaning for the column 'mood':


1. Sorting by Positivity Level:
- elated (highly positive mood)
- content (neutral to slightly positive mood)
- depressed (highly negative mood)
Explanation: This sorting is based on the emotional intensity and positivity of each mood, with elated being the most positive, content being neutral to slightly positive, and depressed being the most negative.


2. Sorting by Emotional Intensity:
- elated (highly intense positive mood)
- depressed (highly intense negative mood)
- content (moderate, balanced mood)
Explanation: This sorting places the moods in order of their emotional intensity, with elated and depressed representing strong emotions at opposite ends of the spectrum, while content falls in the middle with a moderate emotional level.


3. Sorting by Emotional State:
- elated (extremely happy and joyful mood)
- content (satisfied and peaceful mood)
- depressed (sad and unhappy mood)
Explanation: This sorting categorizes the moods based on the general emotional state they represent, with elated indicating extreme happiness, content suggesting satisfaction and peace, and depressed reflecting sadness and unhappiness.


4. Sorting by Emotional Impact:
- elated (highly impactful positive mood)
- depressed (highly impactful negative mood)
- content (moderate, balanced mood)
Explanation: This sorting orders the moods based on their potential impact on an individual's emotional well-being, with elated and depressed having significant impacts at opposite ends, while content denotes a more stable and balanced emotional state.


5. Sorting by Emotional Polarization:
- elated (extreme positive mood)
- content (neutral mood)
- depressed (extreme negative mood)
Explanation: This sorting arranges the moods based on their emotional polarization, with elated and depressed representing the extreme ends of positivity and negativity respectively, while content falls in the middle as a neutral mood state.

In [ ]:
languages = semantic_cort_column('language', 'English, French, Mandarin, Spanish')

In [ ]:
languages

'1. Sort based on geographical spread:\n- Mandarin (spoken in China and other parts of East Asia)\n- Spanish (spoken in Spain and many countries in Latin America)\n- English (spoken in many countries around the world)\n- French (spoken in France and former French colonies)\n\n2. Sort based on number of native speakers:\n- Mandarin (most spoken language in the world by native speakers)\n- Spanish (second most spoken language in the world by native speakers)\n- English (third most spoken language in the world by native speakers)\n- French (sixth most spoken language in the world by native speakers)\n\n3. Sort based on language family:\n- Mandarin (Sino-Tibetan language family)\n- English (Indo-European language family)\n- French (Indo-European language family)\n- Spanish (Indo-European language family)\n\n4. Sort based on official language status:\n- English (official language in many countries, including the UK, USA, Canada, Australia)\n- Spanish (official language in 21 countries)\n- French (official language in 29 countries)\n- Mandarin (official language in China)\n\n5. Sort based on historical influence:\n- English (global lingua franca due to British colonial history and US cultural influence)\n- French (historical language of diplomacy and culture, former lingua franca)\n- Spanish (colonial language in many parts of the Americas)\n- Mandarin (historical importance in Chinese culture and civilization)'

In [ ]:
language_sortings = languages.split('\n\n')

In [ ]:
for suggestion in language_sortings:
  print(suggestion)
  print()
  print()

1. Sort based on geographical spread:
- Mandarin (spoken in China and other parts of East Asia)
- Spanish (spoken in Spain and many countries in Latin America)
- English (spoken in many countries around the world)
- French (spoken in France and former French colonies)


2. Sort based on number of native speakers:
- Mandarin (most spoken language in the world by native speakers)
- Spanish (second most spoken language in the world by native speakers)
- English (third most spoken language in the world by native speakers)
- French (sixth most spoken language in the world by native speakers)


3. Sort based on language family:
- Mandarin (Sino-Tibetan language family)
- English (Indo-European language family)
- French (Indo-European language family)
- Spanish (Indo-European language family)


4. Sort based on official language status:
- English (official language in many countries, including the UK, USA, Canada, Australia)
- Spanish (official language in 21 countries)
- French (official language in 29 countries)
- Mandarin (official language in China)


5. Sort based on historical influence:
- English (global lingua franca due to British colonial history and US cultural influence)
- French (historical language of diplomacy and culture, former lingua franca)
- Spanish (colonial language in many parts of the Americas)
- Mandarin (historical importance in Chinese culture and civilization)

### Semantic sort using multitple columns

#### getting column name (in case of ambiguous names)

In [ ]:
def get_column_name(values, mod="3.5-turbo"):

  prompt = f"Given the sample values [{values}], what is the most likely name for this column?. Give an answer which is as accuracte as possible and give only the column name."
  response = openai.ChatCompletion.create(
      model=f"gpt-{mod}",
      messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
      max_tokens=1000,
      n=1,
      stop=None,
      temperature=0.7
  )

  return response.choices[0].message['content']

In [ ]:
prog_language_col = get_column_name('JavaScript, Python, C++, Ruby, JavaScript, Perl', "4o")

In [ ]:
prog_language_col

'Programming_Languages'

In [ ]:
job_level_col = get_column_name('Intern, Junior, Associate, Lead, Manager, Senior, Executive, Director', "4o")

In [ ]:
job_level_col

'Job Title'

In [ ]:
degree_col = get_column_name("High School, Associate Degree, Bachelor's, Master's, PhD", "4o")

In [ ]:
degree_col

'Education Level'

#### generating columns which can be used together to sort the table

In [ ]:
def get_multiple_columns_suggestions(columns, mod='3.5-turbo'):

  '''
    given column names, determine which can be used together to semantically sort the table
  '''

  prompt = f"Given the columns {columns}, determine which columns can be used together to do semantic sorting of the dataset. Focus on columns that have hierarchical, contextual, or categorical relationships/values. Explicitly exclude columns that are primary keys, contain people's names, unique identifiers, or any other columns that cannot be sorted semantically. For each suggested pair of columns, provide a reasoning for their selection, ensuring they are suitable for semantic sorting and do not include primary keys or identifiers. Provide the answer in the format [column1, column2]. Explanation: reasoning about why these columns can be used together to do semantic sorting. Give as many as 5 suggestions with the most probable first."
  response = openai.ChatCompletion.create(
      model=f"gpt-{mod}",
      messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
      max_tokens=1000,
      n=1,
      stop=None,
      temperature=0.7
  )

  return response.choices[0].message['content']

In [ ]:
ex1 = get_multiple_columns_suggestions('Employee Name, Job Level, Mood, Education Level, Department')

In [ ]:
final_ex1 = ex1.split('\n\n')
for suggestion in final_ex1:
  print(suggestion)
  print('\n\n')

1. **[Job Level, Education Level]**
   - **Reasoning:** Job Level and Education Level have a hierarchical relationship where typically higher education levels correspond to higher job levels. This relationship allows for meaningful sorting based on the level of education required for different job levels.



2. **[Department, Job Level]**
   - **Reasoning:** Departments often have specific job levels assigned to them based on the hierarchy within the organization. Sorting based on Department and Job Level can provide insights into the organizational structure and the distribution of job levels across different departments.



3. **[Education Level, Department]**
   - **Reasoning:** Education Level and Department may exhibit a contextual relationship where certain departments require specific levels of education for roles within them. Sorting based on these columns could help in understanding the educational requirements across different departments.



4. **[Department, Mood]**
   - **Reasoning:** Department and Mood could be related in a categorical manner where the mood of employees within a department may vary based on factors specific to that department's work environment or culture. Sorting based on Department and Mood could help in analyzing employee sentiments within different departments.



5. **[Job Level, Mood]**
   - **Reasoning:** Job Level and Mood could be used for sorting to understand the emotional well-being or job satisfaction levels across different job levels. This could provide insights into how mood varies based on the hierarchical position within the organization.



These column pairs are suitable for semantic sorting as they involve hierarchical, contextual, or categorical relationships/values that can provide meaningful insights when sorted together.

In [ ]:
ex2 = get_multiple_columns_suggestions('Position, Experience Level, Urgency of Task, Performance Rating, Project Phase', "4o")

In [ ]:
final_ex2 = ex2.split('\n\n')
for suggestion in final_ex2:
  print(suggestion)
  print('\n\n')

1. **[Position, Experience Level]**
   - **Explanation:** Sorting by Position can be hierarchically meaningful as job roles often follow a clear progression (e.g., Junior Developer < Senior Developer < Team Lead). When combined with Experience Level, it allows for further refinement within each position, prioritizing more experienced individuals within the same role.



2. **[Experience Level, Performance Rating]**
   - **Explanation:** This combination allows for semantic sorting where employees are first grouped by their level of experience (e.g., Intern < Junior < Mid-Level < Senior), and then sorted within each group by their performance rating. This is useful for evaluating how well employees at different experience levels are performing.



3. **[Urgency of Task, Project Phase]**
   - **Explanation:** Sorting tasks by urgency is critical in project management. When combined with Project Phase, it enables sorting tasks in a way that prioritizes urgent tasks within each specific phase of the project (e.g., Planning, Execution, Closure), ensuring that high-priority tasks in the current phase are addressed first.



4. **[Performance Rating, Position]**
   - **Explanation:** This allows for a ranking of employees based on their performance rating, which can be further contextualized by their position. For example, it differentiates high-performing junior staff from high-performing senior staff, which can be significant for performance evaluations and promotions.



5. **[Project Phase, Experience Level]**
   - **Explanation:** This combination is useful for assigning tasks or responsibilities within a project. Sorting by Project Phase ensures that tasks are organized according to the project's progression. Within each phase, sorting by Experience Level helps in assigning more complex tasks to more experienced individuals, ensuring that the right skills are applied at the right time.

In [ ]:
def semantic_sort_multiple_column(column1, values1, column2, values2, mod='3.5-turbo'):
  prompt = f"Given the columns {column1} with values [{values1}] and {column2} with values [{values2}], provide a semantic sorting of the combined values of these columns. Explain the sorting criteria for the combined column, including the rationale behind why certain values come before others and what world knowledge is considered for this purpose if any. Try to avoid alphabetical sorting and use context and semantic relationships Give the results as accurate and relevant as possible"

  response = openai.ChatCompletion.create(
      model=f"gpt-{mod}",
      messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
      max_tokens=1000,
      n=1,
      stop=None,
      temperature=0.7
  )

  return response.choices[0].message['content']

#### getting combined column values

In [ ]:
def semantic_sort_multiple_column2(column1, values1, column2, values2, mod='3.5-turbo'):
  prompt = f"Given the columns {column1} with values {values1} and {column2} with values {values2}, generate all unique combinations of values from these columns, and then provide a semantic sorting of these combined values. Explain the sorting criteria for the combined values, including the rationale behind why certain combinations come before others and what world knowledge is considered for this purpose, if any. Try to avoid alphabetical sorting and use context and semantic relationships. Provide the results as accurately and relevantly as possible."
  response = openai.ChatCompletion.create(
      model=f"gpt-{mod}",
      messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
      max_tokens=1000,
      n=1,
      stop=None,
      temperature=0.7
  )

  return response.choices[0].message['content']

In [ ]:
def semantic_sort_multiple_columns_all_rows(column1, values1, column2, values2, mod='3.5-turbo'):
  '''
  Giving all rows consisting of specific columns and asking to sort them semantically.

  '''
  if len(values1) != len(values2):
        raise ValueError("The length of values1 and values2 must be the same")

  combined_values = [(v1, v2) for v1, v2 in zip(values1, values2)]

  prompt = f"""
    Given two columns '{column1}' with values {values1} and '{column2}' with values {values2}, you have specific row values from these columns. Please sort these rows semantically based on the combined values of both columns. The sorting should be contextual and consider real-world knowledge and relationships rather than simple alphabetical order.
For each row, consider how the values in '{column1}' and '{column2}' interact and influence the ranking. Explain the rationale behind the sorting criteria, detailing why certain rows are prioritized over others. Consider hierarchical, contextual, or categorical relationships, and exclude primary keys, names, or other non-semantically sortable columns. Provide the sorted rows and the reasoning behind their order as accurately and relevantly as possible.
Here are the rows: {combined_values}
"""

    # Make the API call to OpenAI
  response = openai.ChatCompletion.create(
        model=f"gpt-{mod}",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=1000,
        n=1,
        stop=None,
        temperature=0.7
    )

  return response.choices[0].message['content']

In [ ]:
# Example for semantic_sort_multiple_columns_all_rows

column1 = "Job Title"
values1 = ["Senior Engineer", "Junior Engineer", "Junior Engineer", "Manager", "Manager"]
column2 = "Location"
values2 = ["California", "New York", "California", "Utah", "California"]

response = semantic_sort_multiple_columns_all_rows(column1, values1, column2, values2, mod='4o')
final = response.split("\n\n")
for suggestion in final:
  print(suggestion)
  print("\n")

To sort the rows semantically based on the 'Job Title' and 'Location' columns, we should consider the hierarchical nature of job titles as well as the perceived desirability and relevance of the locations in a professional context.


### Job Title Hierarchy:
1. Manager
2. Senior Engineer
3. Junior Engineer


### Location Importance (assuming tech industry context):
1. California (major tech hub)
2. New York (significant tech presence)
3. Utah (less prominent tech hub)


### Sorted Rows:
1. **Manager, California**
2. **Senior Engineer, California**
3. **Manager, Utah**
4. **Junior Engineer, California**
5. **Junior Engineer, New York**


### Reasoning:


1. **Manager, California**:
   - **Job Title:** 'Manager' is the highest-ranking position among the given titles.
   - **Location:** California is a major tech hub, making it a highly desirable location for a managerial position.


2. **Senior Engineer, California**:
   - **Job Title:** 'Senior Engineer' is ranked below 'Manager' but above 'Junior Engineer'.
   - **Location:** California's tech prominence makes this position highly valuable.


3. **Manager, Utah**:
   - **Job Title:** 'Manager' still holds a high rank.
   - **Location:** While Utah is less prominent than California, a managerial role holds significant importance.


4. **Junior Engineer, California**:
   - **Job Title:** 'Junior Engineer' is the lowest-ranking position.
   - **Location:** California's tech industry prominence elevates the importance of even entry-level roles.


5. **Junior Engineer, New York**:
   - **Job Title:** 'Junior Engineer' is the lowest-ranking position.
   - **Location:** New York has a significant but less central tech presence compared to California, making this the least prioritized row.


By combining the hierarchical status of job titles with the contextual importance of their locations, we can derive a semantically meaningful order for these rows.

In [ ]:
pos_exp_3 = semantic_sort_multiple_column("Position", "Intern, Junior Developer, Senior Developer, Team Lead, Manager", "Experience_Level", "Entry Level, Mid Level, Senior Level", "4o")

In [ ]:
final_pos_exp_3 = pos_exp_3.split("\n\n")
for suggestion in final_pos_exp_3:
  print(suggestion)
  print("\n")

To semantically sort the combined values of `Position` and `Experience_Level`, we need to consider the typical career progression in the tech industry, where certain roles are inherently associated with certain levels of experience. Here's a plausible sorting:


1. Intern - Entry Level
2. Junior Developer - Entry Level
3. Junior Developer - Mid Level
4. Senior Developer - Mid Level
5. Senior Developer - Senior Level
6. Team Lead - Senior Level
7. Manager - Senior Level


### Sorting Criteria and Rationale:


1. **Career Progression:**
   - Interns are usually at the entry level since the role is designed to provide initial industry exposure.
   - Junior Developers are typically the next step up from Interns and can span from entry to mid-level experience.
   - Senior Developers are generally expected to have mid to senior-level experience due to the complexity and responsibility of their tasks.
   - Team Leads and Managers are commonly senior-level roles as they require substantial experience and leadership skills.


2. **Role Responsibilities:**
   - Higher-responsibility roles like Team Lead and Manager are placed later in the sequence as they demand more experience and expertise.
   - Roles that involve direct contribution (like Junior and Senior Developers) come before leadership roles (Team Lead, Manager), reflecting the typical career ladder in tech.


3. **Industry Norms and Expectations:**
   - The tech industry typically follows a path from entry-level positions (Intern, Junior Developer) to more advanced contributor roles (Senior Developer) and finally to leadership roles (Team Lead, Manager).


### Semantic Sorting:


1. **Intern - Entry Level:** The starting point for many careers, typically requiring minimal experience.
2. **Junior Developer - Entry Level:** The next step after an internship, still at an entry-level but with more responsibilities.
3. **Junior Developer - Mid Level:** More experienced than entry-level, but still learning and growing in their role.
4. **Senior Developer - Mid Level:** An experienced developer who has not yet reached the highest levels of seniority.
5. **Senior Developer - Senior Level:** A highly experienced developer, often involved in complex projects and mentoring juniors.
6. **Team Lead - Senior Level:** A senior-level role with leadership responsibilities, often overseeing a team of developers.
7. **Manager - Senior Level:** A senior-level role focused on broader management responsibilities, including strategic planning and overseeing multiple teams or projects.


This sorting respects the natural progression in career development and the increasing levels of responsibility and expertise required for each subsequent role.

In [ ]:
pos_exp = semantic_sort_multiple_column2("Position", "Intern, Junior Developer, Senior Developer, Team Lead, Manager", "Experience_Level", "Entry Level, Mid Level, Senior Level", "4o")

In [ ]:
final_pos_exp = pos_exp.split("\n\n")
for suggestion in final_pos_exp:
  print(suggestion)
  print("\n")

To provide a meaningful and contextually relevant sorting of the combinations of the Position and Experience_Level values, we need to base our criteria on typical career progression and the inherent hierarchy within job titles and experience levels.


### Sorting Criteria:
1. **Position Hierarchy**: The positions will be sorted based on a typical career ladder in the tech industry.
    - Intern
    - Junior Developer
    - Senior Developer
    - Team Lead
    - Manager


2. **Experience Level within Each Position**: For each position, the experience levels will be sorted from least experienced to most experienced.
    - Entry Level
    - Mid Level
    - Senior Level


This sorting reflects the typical progression and increasing responsibility in a technology career.


### Sorted Combinations:
1. Intern - Entry Level
2. Intern - Mid Level
3. Intern - Senior Level
4. Junior Developer - Entry Level
5. Junior Developer - Mid Level
6. Junior Developer - Senior Level
7. Senior Developer - Entry Level
8. Senior Developer - Mid Level
9. Senior Developer - Senior Level
10. Team Lead - Entry Level
11. Team Lead - Mid Level
12. Team Lead - Senior Level
13. Manager - Entry Level
14. Manager - Mid Level
15. Manager - Senior Level


### Explanation of Sorting:
- **Intern**: This is typically the starting point for most individuals, often students or recent graduates with little to no professional experience.
- **Junior Developer**: This is the next step after an internship or entry-level position, where individuals start taking on more responsibility.
- **Senior Developer**: This position typically follows a junior role and involves more complex tasks and possibly mentoring less experienced developers.
- **Team Lead**: This role often involves leading a team of developers, requiring substantial experience and leadership skills.
- **Manager**: This is a higher-level position that usually oversees multiple teams or a significant portion of a project or department, requiring the most experience.


By sorting in this manner, we reflect real-world career progression and the increasing responsibilities associated with each role and experience level.

In [ ]:
prod_stock_3 = semantic_sort_multiple_column("Product Category", "Electronics, Furniture, Clothing, Toys", "Stock Status", "In Stock, Out of Stock, Discontinued" )

In [ ]:
final_prod_stock_3 = prod_stock_3.split("\n\n")
for suggestion in final_prod_stock_3:
  print(suggestion)
  print("\n")

To provide a semantic sorting of the combined values of the columns Product Category and Stock Status, we can consider the following criteria:


1. Priority based on availability:
   - In Stock: Items that are currently available for purchase should be prioritized.
   - Out of Stock: Items that are temporarily unavailable may come next in the sorting.
   - Discontinued: Items that are no longer produced or available should be at the bottom of the sorting.


2. General product categories:
   - Electronics: This category typically includes products that are in high demand and have a significant impact on daily life, so they can be placed at the top.
   - Furniture: Furniture is essential but might have lower urgency compared to electronics.
   - Clothing: Clothing is a common necessity but may have varying demand levels based on trends and seasons.
   - Toys: Toys are often considered non-essential and may have lower priority compared to other categories.


Based on these criteria, a semantic sorting of the combined values of Product Category and Stock Status would be as follows:


1. Electronics - In Stock
2. Electronics - Out of Stock
3. Electronics - Discontinued
4. Furniture - In Stock
5. Furniture - Out of Stock
6. Furniture - Discontinued
7. Clothing - In Stock
8. Clothing - Out of Stock
9. Clothing - Discontinued
10. Toys - In Stock
11. Toys - Out of Stock
12. Toys - Discontinued


This sorting reflects the importance of availability and demand for each product category, with priority given to currently available items within each category.

In [ ]:
course_diff_3 = semantic_sort_multiple_column("Course Level", "Undergraduate, Graduate, Postgraduate", "Course Difficulty", "Beginner, Intermediate, Advanced")

In [ ]:
final_course_diff_3 = course_diff_3.split("\n\n")
for suggestion in final_course_diff_3:
  print(suggestion)
  print("\n")

To create a combined column for Course Level and Course Difficulty, we need to consider a semantic sorting that makes sense in the context of education and learning progression. Below is the semantic sorting that takes into account the logical progression of difficulty levels within each course level:


1. Undergraduate Beginner
2. Undergraduate Intermediate
3. Undergraduate Advanced
4. Graduate Beginner
5. Graduate Intermediate
6. Graduate Advanced
7. Postgraduate Beginner
8. Postgraduate Intermediate
9. Postgraduate Advanced


The rationale behind this sorting is based on the typical educational journey of a student. In general, undergraduate courses are considered foundational, so they start with Beginner level courses and progress to Intermediate and then Advanced levels. Similarly, for Graduate and Postgraduate levels, the difficulty level is expected to increase as students move from Beginner to Advanced.


This sorting aligns with the common understanding that courses at higher levels of education are expected to be more challenging and in-depth compared to lower levels. It also reflects the progression of knowledge and skills that students are expected to acquire as they advance through their academic careers.


Please let me know if you need further assistance or clarification.

### Semantic sort using multiple columns by trying to generate a new column

1. Tried with ChatGPT interface, not giving good results.
2. Have to modify prompts and try again

In [ ]:
import pandas as pd

def create_and_sort_new_column(df, column1, column2, mod="3.5-turbo"):
    values1 = df[column1].unique().tolist()
    values2 = df[column2].unique().tolist()

    # prompt3 = f"""
    #       I am working on a semantic sort problem, where a dataset will be sorted based on the values of a column semantically. For example,
    #       if there is a column 'job_level' with unique values 'senior', 'junior', and 'associate', the data should be sorted based on the semantic meanings
    #       of these values, i.e., senior should come first, then associate, then junior. Given two columns, {column1} with unique values {values1} and
    #       {column2} with values unique {values2}, create a new column that reflects the semantic relationships between these columns. The new column should
    #       not simply combine or replicate the values from both columns. There should be minimal overlap between the values of the new column and the original columns.
    #       Multiple original values should map to a single new value, ensuring the new column can be used effectively for semantic sorting. This new column should uniquely
    #       and meaningfully capture the semantic relationships between {column1} and {column2}, using world knowledge and contextual understanding to create values suitable
    #       for semantically sorting the dataset. Please provide an appropriate name for this new column, the new column values, and an explanation of the criteria for the
    #       new column values, including the rationale behind the ordering of the values and any world knowledge considered. Additionally, include a mapping from each unique pair of the
    #       original column values (col1_value, col2_value -> new_col_value) to the new values and all new values should not be unique, they have to be used for semantically sorting the table.
    #       Avoid alphabetical sorting and prioritize context and semantic relationships.
    #       Ensure that the new column values can be used to semantically sort the dataset and that they map to multiple rows.
    # """

    prompt2 = f"""
          Given two columns, '{column1}' with unique values {values1} and '{column2}' with unique values {values2}, create a new column that
          reflects the semantic relationships between these columns. The new column should not simply combine or replicate the values from both columns.
          There should be minimal overlap between the values of the new column and the original columns. This new column should uniquely and meaningfully
          capture the semantic relationships between '{column1}' and '{column2}', using world knowledge and contextual understanding to create values suitable
          for semantically sorting the dataset. This new column should uniquely
          and meaningfully capture the semantic relationships between {column1} and {column2}, using world knowledge and contextual understanding to create values suitable
          for semantically sorting the dataset.

          Please provide an appropriate name for this new column, the new column values, and an explanation of the criteria for the new column values,
          including the rationale behind the ordering of the values and any world knowledge considered. Additionally, include a mapping from the original
          column values (col1_value, col2_value -> new_col_value) to the new values. Avoid alphabetical sorting and prioritize context and semantic relationships.
          Ensure that the new column values can be used to semantically sort the dataset and that they map to multiple rows.

    """

    # prompt = f"""
    #     Given two columns, '{column1}' with unique values {values1} and '{column2}' unique with values {values2}, create a new column based on the semantic
    #     relationships between these columns. The new column should not simply combine or replicate the values from both columns, and there should be
    #     minimal intersection between the values of the new column and the original columns. This new column should uniquely and meaningfully reflect the
    #     semantic relationships between '{column1}' and '{column2}', leveraging world knowledge and contextual understanding to create values that are suitable
    #     for semantically sorting the table.

    #     Please determine an appropriate name for this new column and explain the criteria for the new column values, including the rationale
    #     behind the ordering of the values and what world knowledge is considered for this purpose. Avoid alphabetical sorting and prioritize context
    #     and semantic relationships. Provide the new column name and its values, and explain the mapping from the two original column values (col1_value, col2_value -> new_col_value) to the new value.
    #     Note that the values in column 1 and column 2 are distinct and are not assumed to be from the same rows.
    #     Ensure that the new column values can be used to semantically sort the dataset and that they map to multiple rows.

    # """
    response = openai.ChatCompletion.create(
      model=f"gpt-{mod}",
      messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt2}
        ],
      max_tokens=1000,
      n=1,
      stop=None,
      temperature=0.7
  )
    result = response.choices[0].message['content']
    print(result)

In [ ]:
products_data = {
    'ProductID': [1, 2, 3, 4, 5, 6],
    'ProductName': ['Laptop', 'Desk Chair', 'Smartphone', 'Bookshelf', 'Tablet', 'Office Lamp'],
    'Category': ['Electronics', 'Furniture', 'Electronics', 'Furniture', 'Electronics', 'Furniture'],
    'PopularityLevel': ['High', 'Medium', 'High', 'Low', 'Medium', 'Low']
}
products_df = pd.DataFrame(products_data)
columns = products_df.columns.tolist()
print("Columns:", columns)
suitable_columns = get_multiple_columns_suggestions(columns, "4o")
print("Suitable columns for semantic sorting:", suitable_columns)

Columns: ['ProductID', 'ProductName', 'Category', 'PopularityLevel']
Suitable columns for semantic sorting: Here are some suggestions for column pairs that can be used for semantic sorting of the dataset, excluding primary keys or unique identifiers:

1. **[Category, PopularityLevel]**
   - **Explanation**: The "Category" column can be used to group products into meaningful categories, while "PopularityLevel" can be used to sort products within each category based on their popularity. This allows for a hierarchical sorting where products are first grouped by their type and then ordered by their popularity within those groups.

2. **[PopularityLevel, Category]**
   - **Explanation**: This pair can be used to sort products primarily by their popularity and then by category. This is useful when you want to see the most popular items first, regardless of their category, but still want to maintain a secondary order based on the type of product.

3. **[Category, ProductName]**
   - **Explanation**: Sorting by "Category" first and then by "ProductName" allows for a semantic organization where products are grouped by type and then alphabetically within each type. This is helpful for users who are looking for products within a specific category and want them listed in a readable, alphabetical order.

4. **[PopularityLevel, ProductName]**
   - **Explanation**: This pair can be used to sort products primarily by their popularity level and then alphabetically by their names. This way, the most popular products are listed first, but within each popularity level, they are sorted alphabetically for ease of browsing.

5. **[ProductName, Category]**
   - **Explanation**: Sorting primarily by "ProductName" and then by "Category" can be useful in scenarios where users are looking for a specific product name and want to see all similar products grouped by category. This can be particularly helpful in large datasets where similar products might have names that are close alphabetically but belong to different categories.

These column pairs provide meaningful ways to organize and browse the dataset without relying on primary keys or unique identifiers.

In [ ]:
create_and_sort_new_column(products_df, "Category", "PopularityLevel", "4o")

### New Column: "MarketInfluence"

#### Explanation and Criteria:
The "MarketInfluence" column is designed to reflect the combined impact of both the product category and its popularity level on the market. This column captures the perceived influence and demand of items in the market, taking into account how much consumers need or desire these items and how frequently they are bought.

- **Electronics** are generally high-turnover items with rapid innovation cycles, thus having a higher impact on the market.
- **Furniture** tends to have longer usage cycles and less frequent purchases, generally perceived as lower impact in terms of market dynamics.

**Popularity Level Impact:**
- **High** Popularity: Indicates a strong consumer demand and frequent purchase.
- **Medium** Popularity: Represents moderate demand and purchase frequency.
- **Low** Popularity: Denotes minimal demand and infrequent purchase.

The priority ranking for "MarketInfluence" is based on a synthesis of these factors:

1. **Electronics with High Popularity** - Highest market influence due to rapid turnover and strong demand.
2. **Furniture with High Popularity** - Significant influence due to strong demand.
3. **Electronics with Medium Popularity** - Moderate influence, balancing high turnover with moderate demand.
4. **Furniture with Medium Popularity** - Moderate influence, balancing lower turnover with moderate demand.
5. **Electronics with Low Popularity** - Lower influence due to infrequent purchase.
6. **Furniture with Low Popularity** - Lowest influence due to both infrequent purchase and lower turnover.

### Mapping from Original Columns to New Column:

| Category     | PopularityLevel | MarketInfluence         |
|--------------|-----------------|-------------------------|
| Electronics  | High            | Top Demand              |
| Furniture    | High            | High Demand             |
| Electronics  | Medium          | Moderate Demand         |
| Furniture    | Medium          | Steady Demand           |
| Electronics  | Low             | Niche Demand            |
| Furniture    | Low             | Low Demand              |

### Semantic Sorting Order:
1. **Top Demand** - Highest market influence.
2. **High Demand** - High market influence.
3. **Moderate Demand** - Moderate market influence.
4. **Steady Demand** - Moderate market influence but slightly lower.
5. **Niche Demand** - Lower market influence.
6. **Low Demand** - Lowest market influence.

### Mapping:
- (Electronics, High) -> Top Demand
- (Furniture, High) -> High Demand
- (Electronics, Medium) -> Moderate Demand
- (Furniture, Medium) -> Steady Demand
- (Electronics, Low) -> Niche Demand
- (Furniture, Low) -> Low Demand

This mapping ensures that the new "MarketInfluence" column captures a meaningful and contextually appropriate influence on the market, allowing the dataset to be semantically sorted based on perceived market impact.

In [ ]:
courses_data = {
    'CourseID': [1, 2, 3, 4, 5, 6],
    'CourseName': ['Introduction to AI', 'Advanced AI', 'Data Structures', 'Calculus I', 'Linear Algebra', 'Machine Learning'],
    'CourseType': ['Science', 'Science', 'Engineering', 'Mathematics', 'Mathematics', 'Science'],
    'DifficultyLevel': ['Beginner', 'Advanced', 'Intermediate', 'Beginner', 'Intermediate', 'Intermediate']
}

courses_df = pd.DataFrame(courses_data)

print(courses_df)
columns = courses_df.columns.tolist()
print("Columns:", columns)
suitable_columns = get_multiple_columns_suggestions(columns, "4o")
print("Suitable columns for semantic sorting:", suitable_columns)

   CourseID          CourseName   CourseType DifficultyLevel
0         1  Introduction to AI      Science        Beginner
1         2         Advanced AI      Science        Advanced
2         3     Data Structures  Engineering    Intermediate
3         4          Calculus I  Mathematics        Beginner
4         5      Linear Algebra  Mathematics    Intermediate
5         6    Machine Learning      Science    Intermediate
Columns: ['CourseID', 'CourseName', 'CourseType', 'DifficultyLevel']
Suitable columns for semantic sorting: 1. **[CourseType, DifficultyLevel]**
   - **Explanation**: CourseType typically categorizes courses into different domains or fields (e.g., Science, Arts, Technology), and within each domain, DifficultyLevel (e.g., Beginner, Intermediate, Advanced) provides a hierarchical context. Sorting courses first by CourseType and then by DifficultyLevel allows users to see the progression of courses within each domain.

2. **[CourseName, DifficultyLevel]**
   - **Explanation**: CourseName often provides a contextual understanding of the content, and DifficultyLevel adds an additional layer of semantic sorting. Sorting by CourseName first groups courses with similar topics, and then DifficultyLevel organizes them by the complexity, helping users find courses that match their skill level within a specific subject.

3. **[CourseType, CourseName]**
   - **Explanation**: Sorting by CourseType groups courses into their respective fields or categories, and CourseName further sorts them alphabetically or contextually within each type. This makes it easier to navigate through courses based on their category and then by specific names.

4. **[DifficultyLevel, CourseType]**
   - **Explanation**: Starting the sort with DifficultyLevel groups courses by complexity, and then CourseType provides an organizational structure within each level. This is useful for users who want to start with their preferred difficulty level and then choose from different types of courses available at that level.

5. **[DifficultyLevel, CourseName]**
   - **Explanation**: Sorting first by DifficultyLevel allows users to see courses organized by complexity, and then CourseName sorts them alphabetically or contextually within each difficulty level. This helps users find courses appropriate for their skill level while maintaining an organized list based on the course titles.

In [ ]:
create_and_sort_new_column(courses_df, "CourseType", "DifficultyLevel")

**New Column Name:** Skill Level

**New Column Values:**
- Foundational
- Proficient
- Specialized

**Criteria and Rationale:**
The new column "Skill Level" is designed to capture the progression of expertise within the context of courses related to Science, Engineering, and Mathematics. The values are chosen based on the logical progression of skills and knowledge acquisition.

- **Foundational:** This value represents a basic understanding or entry-level knowledge in a particular field. Courses designated as "Beginner" in DifficultyLevel would align with this level, indicating fundamental concepts and skills.

- **Proficient:** This value signifies a higher level of competence and expertise beyond the basics. Courses labeled as "Intermediate" in DifficultyLevel would correspond to this level, indicating a solid grasp of concepts and the ability to apply them effectively.

- **Specialized:** This value indicates a deep and specific expertise within a particular area. Courses marked as "Advanced" in DifficultyLevel would be associated with this level, indicating a mastery of complex topics and advanced skills within the subject matter.

**Mapping:**
- Science, Beginner -> Foundational
- Science, Intermediate -> Proficient
- Science, Advanced -> Specialized
- Engineering, Beginner -> Foundational
- Engineering, Intermediate -> Proficient
- Engineering, Advanced -> Specialized
- Mathematics, Beginner -> Foundational
- Mathematics, Intermediate -> Proficient
- Mathematics, Advanced -> Specialized

This new column "Skill Level" provides a meaningful and structured way to understand and sort the dataset based on the expertise level required in Science, Engineering, and Mathematics courses.

In [ ]:
create_and_sort_new_column(courses_df, "CourseType", "DifficultyLevel") # hallucinated

Certainly! For the given columns CourseType and DifficultyLevel, we can create a new column named "AcademicChallenge" that reflects the semantic relationships between the two columns. The new column will capture the level of academic rigor or complexity associated with each course based on both the course type and difficulty level.

Here is the mapping from unique pairs of original column values to the new column values:

1. Science, Beginner -> Introductory
2. Science, Intermediate -> Fundamental
3. Science, Advanced -> Complex
4. Engineering, Beginner -> Foundational
5. Engineering, Intermediate -> Applied
6. Engineering, Advanced -> Cutting-edge
7. Mathematics, Beginner -> Elementary
8. Mathematics, Intermediate -> Theoretical
9. Mathematics, Advanced -> Advanced

Explanation of the criteria for the new column values:

- The new column values are designed to reflect a progression in the level of academic challenge or complexity, considering both the course type and difficulty level.
- The ordering of the new values is based on the typical progression of difficulty and complexity in academic fields, with introductory and foundational concepts coming first, followed by more specialized and advanced topics.
- World knowledge and contextual understanding have been used to assign values that are meaningful and intuitive in the educational domain, ensuring that the new column can be effectively used for semantic sorting.

The new column "AcademicChallenge" and its values provide a clear indication of the academic complexity associated with each course, allowing for meaningful sorting and categorization based on the level of challenge presented by the courses.

In [ ]:
exhibition_data1 = {
    "Exhibition Name": [
        "Renaissance Art", "Modern Abstract", "Impressionist Era", "Baroque Masterpieces",
        "Contemporary Vision", "Surrealist Dreams", "Renaissance Revival", "Abstract Revolution",
        "Impressionist Insights", "Baroque Wonders", "Modern Marvels", "Surrealist Fantasies"
    ],
    "Art Style": [
        "Renaissance", "Abstract", "Impressionism", "Baroque",
        "Contemporary", "Surrealism", "Renaissance", "Abstract",
        "Impressionism", "Baroque", "Contemporary", "Surrealism"
    ],
    "City": [
        "Florence", "New York", "Paris", "Rome", "Berlin", "Madrid",
        "Florence", "Los Angeles", "Paris", "Rome", "Chicago", "Madrid"
    ],
    "Year": [
        2020, 2018, 2019, 2021, 2017, 2018, 2022, 2019, 2020, 2021, 2016, 2017
    ],
    "Impact Level": [
        "High", "Medium", "High", "High", "Medium", "Low", "High", "Medium", "High", "High", "Medium", "Low"
    ]
}


exhibition_data2 = {
    "Art Style": [
        "Renaissance", "Abstract", "Impressionism", "Baroque",
        "Contemporary", "Surrealism", "Renaissance", "Abstract",
        "Impressionism", "Baroque", "Contemporary", "Surrealism"
    ],
    "Cultural Impact": [
        "High", "Medium", "High", "High", "Medium", "Medium",
        "High", "Medium", "High", "High", "Medium", "Medium"
    ],
    "Economic Impact": [
        "High", "High", "Medium", "High", "High", "Medium",
        "High", "High", "Medium", "High", "High", "Medium"
    ],
    "Historical Significance": [
        "High", "Low", "High", "High", "Medium", "Medium",
        "High", "Low", "High", "High", "Medium", "Medium"
    ]
}


exhibition_df1 = pd.DataFrame(exhibition_data1)
# df2 = pd.DataFrame(data2)

columns = exhibition_df1.columns.tolist()
print("Columns:", columns)
suitable_columns = get_multiple_columns_suggestions(columns)
print("Suitable columns for semantic sorting:", suitable_columns)

Columns: ['Exhibition Name', 'Art Style', 'City', 'Year', 'Impact Level']
Suitable columns for semantic sorting: 1. ['Art Style', 'Exhibition Name']: Art styles are hierarchical and contextual, and exhibitions are often categorized based on the art style they feature. Sorting by art style first and then by exhibition name would help organize the dataset effectively.

2. ['City', 'Year']: Cities and years have a contextual relationship, as exhibitions are held in specific cities during specific years. Sorting by city first and then by year would provide a logical organization of the dataset.

3. ['Impact Level', 'Exhibition Name']: Impact levels are categorical and exhibitions can be categorized based on their impact level. Sorting by impact level first and then by exhibition name would help identify the most impactful exhibitions.

4. ['Art Style', 'City']: Art styles and cities can be used together for semantic sorting, as certain art styles may be more prevalent in specific cities. Sorting by art style first and then by city would offer a meaningful arrangement of the data.

5. ['Year', 'Art Style']: Years and art styles have a temporal and categorical relationship, as art styles may evolve over time. Sorting by year first and then by art style would provide insights into the evolution of art styles over the years.

In [ ]:
create_and_sort_new_column(exhibition_df1, "Art Style", "Exhibition Name")

**New Column Name:** Artistic Time Period

**New Column Values:**
- **Renaissance and Renaissance Art**: Classic Revival
- **Abstract and Modern Abstract**: Contemporary Expression
- **Impressionism and Impressionist Era**: Timeless Impression
- **Baroque and Baroque Masterpieces**: Ornate Majesty
- **Contemporary and Contemporary Vision**: Modern Interpretation
- **Surrealism and Surrealist Dreams**: Dreamlike Visions

**Criteria for New Column Values:**
The new column values are designed to capture the essence and period-specific characteristics of both the Art Style and Exhibition Name. By combining aspects of both columns, the new values aim to create a meaningful and chronological relationship that reflects the evolution of art styles through time. This approach allows for effective semantic sorting based on the historical context and artistic movements represented in the dataset.

**Rationale for Ordering of Values:**
The ordering of the new column values follows a logical progression based on the historical development of art styles. Starting with the Renaissance as a period of classic revival, the values transition through contemporary expressions and timeless impressions to ornate majesty representing Baroque art. The sequence continues with modern interpretations and concludes with dreamlike visions emblematic of Surrealism. This ordering provides a narrative flow that mirrors the evolution of art movements over time.

**Mapping:**
- **Renaissance, Renaissance Art -> Classic Revival**
- **Abstract, Modern Abstract -> Contemporary Expression**
- **Impressionism, Impressionist Era -> Timeless Impression**
- **Baroque, Baroque Masterpieces -> Ornate Majesty**
- **Contemporary, Contemporary Vision -> Modern Interpretation**
- **Surrealism, Surrealist Dreams -> Dreamlike Visions**

By incorporating historical context, artistic significance, and thematic elements, the new column "Artistic Time Period" offers a cohesive and insightful way to semantically sort the dataset based on the meaningful relationships between the Art Style and Exhibition Name values.

In [ ]:
create_and_sort_new_column(exhibition_df1, "Art Style", "Exhibition Name")

Based on the semantic relationships between the Art Style and Exhibition Name columns, we can create a new column named "Artistic Era" that captures the historical context and thematic essence of the artworks presented in the exhibitions. The new column values will be derived from significant artistic movements and periods that best represent the combination of art style and exhibition theme.

Here are the new column values and their criteria:

1. "Renaissance Masterpieces" - Represents a period of great cultural achievement in art history.
2. "Abstract Expressionism" - Reflects the innovative and non-representational nature of abstract art.
3. "Impressionist Impressions" - Emphasizes the fleeting effects of light and color in impressionist artworks.
4. "Baroque Splendor" - Conveys the dramatic and ornate characteristics of the baroque style.
5. "Contemporary Visions" - Signifies the modern and forward-thinking aspects of contemporary art.
6. "Surrealist Realms" - Captures the dreamlike and subconscious elements of surrealism.

Mapping from original column values to the new column values:

- Renaissance, Renaissance Art -> Renaissance Masterpieces
- Abstract, Modern Abstract -> Abstract Expressionism
- Impressionism, Impressionist Era -> Impressionist Impressions
- Baroque, Baroque Masterpieces -> Baroque Splendor
- Contemporary, Contemporary Vision -> Contemporary Visions
- Surrealism, Surrealist Dreams -> Surrealist Realms

These new column values provide a meaningful and semantically rich way to sort the dataset based on the historical and thematic connections between the art styles and exhibition themes. The ordering of the values reflects the chronological development of art movements and ensures a coherent and informative representation for sorting the dataset effectively.

In [ ]:
employee_data = {
    'EmployeeID': [1, 2, 3, 4, 5, 6],
    'Role': ['Developer', 'Manager', 'Analyst', 'Developer', 'Manager', 'Analyst'],
    'ExperienceLevel': ['Junior', 'Senior', 'Mid', 'Mid', 'Junior', 'Senior']
}

employee_data2 = {
    'EmployeeID': [1, 2, 3, 4, 5, 6],
    'State': ['California', 'Texas', 'New York', 'California', 'Texas', 'Florida'],
    'Salary': [120000, 95000, 110000, 130000, 105000, 90000]
}

employee_df = pd.DataFrame(employee_data)
employee_df2 = pd.DataFrame(employee_data2)

columns = employee_df2.columns.tolist()
print("Columns:", columns)
suitable_columns = get_multiple_columns_suggestions(columns)
print("Suitable columns for semantic sorting:", suitable_columns)

Columns: ['EmployeeID', 'State', 'Salary']
Suitable columns for semantic sorting: 1. ['State', 'Salary']
   - These columns can be used together for semantic sorting because the salary of an employee often varies based on the state they are working in. Sorting by state first can group employees based on their location, and then sorting by salary within each state can provide a meaningful comparison within the same geographic context.

2. ['State', 'EmployeeID']
   - Sorting by state can group employees based on their location, and then sorting by EmployeeID within each state can provide a systematic arrangement of employees within each geographic region.

3. ['State', 'Department']
   - Sorting by state can group employees based on their location, and then sorting by department within each state can provide an organizational hierarchy within each geographic region.

4. ['Department', 'Salary']
   - Sorting by department can group employees based on their role or function within the organization, and then sorting by salary within each department can provide insights into the salary distribution within different job roles.

5. ['State', 'Years of Service']
   - Sorting by state can group employees based on their location, and then sorting by years of service within each state can provide an understanding of how employee tenure varies across different geographic regions.

In [ ]:
create_and_sort_new_column(employee_df, "Role", "ExperienceLevel")

**New Column: Professional_Level**

**New Column Values:**
- Developer, Junior -> Entry Level
- Developer, Mid -> Intermediate Level
- Developer, Senior -> Senior Level
- Manager, Junior -> Team Member
- Manager, Mid -> Team Leader
- Manager, Senior -> Department Head
- Analyst, Junior -> Assistant Analyst
- Analyst, Mid -> Analyst
- Analyst, Senior -> Lead Analyst

**Criteria for New Column Values:**
- The values for the new column are designed based on the typical hierarchical structure and roles found in most organizations.
- The new values capture the progression and expertise level associated with different roles and experience levels.
- The ordering of the values reflects the natural progression in a career, where individuals often start at entry-level positions and move towards more senior roles.
- World knowledge and common workplace hierarchies are considered to ensure the new column values are intuitive and meaningful for semantic sorting.
- The mapping of original column values to the new values is done in a way that multiple original values align with a single new value, providing a clear and concise representation of professional levels.

**Mapping:**
- Developer, Junior -> Entry Level
- Developer, Mid -> Intermediate Level
- Developer, Senior -> Senior Level
- Manager, Junior -> Team Member
- Manager, Mid -> Team Leader
- Manager, Senior -> Department Head
- Analyst, Junior -> Assistant Analyst
- Analyst, Mid -> Analyst
- Analyst, Senior -> Lead Analyst

By incorporating these semantic relationships and career progression patterns, the new column "Professional_Level" offers a meaningful and effective way to sort the dataset based on the professional levels associated with different roles and experience levels.

In [ ]:
create_and_sort_new_column(employee_df2, "State", "Salary")

**New Column Name:** Economic Impact Index

**Criteria and Rationale:**
The new column 'Economic Impact Index' will reflect the combined influence of the State and Salary values in a meaningful and semantically sorted manner. The values in this new column will represent a combination of the economic strength of a state and the level of income represented by the corresponding salary, creating a unique identifier for each combination.

The values in the 'Economic Impact Index' column will be calculated based on a scale that reflects the economic significance of each state and the salary level. States with higher economic impact and higher salaries will be assigned higher values in the index. This will allow for a meaningful sorting of the dataset based on the economic impact of each state-salary pair.

**Mapping:**
- California, 120000 -> 4.3
- California, 95000 -> 3.7
- Texas, 110000 -> 4.1
- Texas, 130000 -> 4.5
- New York, 105000 -> 4.4
- Florida, 90000 -> 3.3

This mapping ensures that each state-salary pair is uniquely represented in the new column, reflecting the economic impact and salary level of each combination. The values in the 'Economic Impact Index' will allow for a meaningful sorting of the dataset based on the economic significance of each state-salary pair.

In [ ]:
# Example 2 # create a promt, where given column names, determine what the dataset is about
data = {
    "Expedition Name": [
        "Deep Sea Exploration", "Coral Reef Survey", "Arctic Ocean Expedition",
        "Mangrove Swamp Study", "Open Ocean Dive", "Kelp Forest Research",
        "Underwater Volcano Expedition", "Seagrass Bed Investigation"
    ],
    "Marine Species": [
        "Giant Squid", "Coral", "Arctic Cod", "Mangrove Snapper", "Blue Whale",
        "Kelp Bass", "Hydrothermal Vent Worm", "Seahorse"
    ],
    "Habitat Depth (meters)": [
        3000, 20, 50, 5, 500, 30, 2500, 10
    ],
    "Conservation Status": [
        "Least Concern", "Endangered", "Near Threatened", "Vulnerable",
        "Endangered", "Least Concern", "Data Deficient", "Least Concern"
    ]
}


df = pd.DataFrame(data)
columns = df.columns.tolist()
suitable_columns = get_multiple_columns_suggestions(columns)
print("Suitable columns for semantic sorting:", suitable_columns)

Suitable columns for semantic sorting: 1. ['Marine Species', 'Conservation Status']
   Explanation: The conservation status of a marine species is often directly related to the species itself, allowing for semantic sorting based on the conservation status of different marine species.

2. ['Habitat Depth (meters)', 'Marine Species']
   Explanation: The habitat depth at which marine species are found can be used to categorize and sort the species based on their preferred environment, providing a hierarchical relationship for semantic sorting.

3. ['Expedition Name', 'Marine Species']
   Explanation: Sorting the dataset based on the expedition name and the marine species observed during each expedition can provide contextual information about where and when specific species were documented.

4. ['Marine Species', 'Habitat Depth (meters)', 'Conservation Status']
   Explanation: Combining these columns allows for sorting based on the relationship between the marine species, their habitat depth preferences, and conservation statuses, providing a comprehensive view of the data.

5. ['Habitat Depth (meters)', 'Conservation Status']
   Explanation: Semantic sorting based on the habitat depth and conservation status can help identify patterns related to the conservation status of species found at different depths in the marine environment.

In [ ]:
create_and_sort_new_column(df, "Conservation Status", "Marine Species")

New Column Name: "Ecosystem Impact"

Criteria for New Column Values:
1. The new column values should reflect the impact of the conservation status of a species on its respective marine ecosystem.
2. Values should be ordered based on the level of impact, with more critical or endangered species having a higher impact value.
3. The mapping from the original columns to the new column should consider the vulnerability of the marine species in relation to its conservation status.

New Column Values and Mapping:
- "Critical Keystone Species" (Endangered, Coral) - Coral reefs are highly sensitive ecosystems, and the endangerment of coral species can have a critical impact on the overall health and biodiversity of the marine ecosystem.
- "Essential Predator" (Near Threatened, Arctic Cod) - Arctic Cod serves as a vital food source for numerous marine predators, and a decline in their population due to being near-threatened can disrupt the food chain in the ecosystem.
- "Key Habitat Engineer" (Vulnerable, Mangrove Snapper) - Mangrove Snappers play a crucial role in shaping and maintaining the habitat structure in mangrove ecosystems, and their vulnerable status signifies potential habitat degradation.
- "Critical Filter Feeder" (Least Concern, Blue Whale) - Blue Whales, despite being listed as least concern, are significant filter feeders that help maintain the balance of marine ecosystems by controlling plankton populations.
- "Foundational Species" (Data Deficient, Kelp Bass) - Kelp Bass, with a data-deficient conservation status, are foundational species providing structure and support for diverse marine communities.
- "Indicator Organism" (Vulnerable, Hydrothermal Vent Worm) - Vulnerable Hydrothermal Vent Worms can serve as indicators of ecosystem health in deep-sea environments due to their sensitivity to changes.
- "Sentinel Species" (Near Threatened, Seahorse) - Near-threatened Seahorses can act as sentinel species, reflecting environmental changes and pollution levels in their habitats.

These new column values provide a meaningful and context-rich representation of the relationship between conservation status and marine species, allowing for a semantic sorting of the dataset based on the ecological impact of each species in its ecosystem.

In [ ]:
def create_and_sort_new_column(df, column1, column2):
    values1 = df[column1].unique().tolist()
    values2 = df[column2].unique().tolist()

    # my initial prompt, works well
    # prompt = f"""Given the columns '{column1}' with values {values1} and '{column2}' with values {values2}, create a new column based on the semantic relationships between these columns. Determine an appropriate name for this new column and explain the criteria for the new column values, including the rationale behind why certain values come before others and what world knowledge is considered for this purpose. Avoid alphabetical sorting and prioritize context and semantic relationships. Provide the new column name and its values. Also explain the mapping from the two original column values to the new value. For simplicity, provide the explanation on the first line, second line should be the new column name, third should be a dictionary with keys as new column names and values as the original column values to map this new column value to. Then after that, explain the reasonings.    """
    prompt2 = f"Given the columns '{column1}' with values {values1} and '{column2}' with values {values2}, create a new column based on the semantic relationships between these columns. Also, consider all the world knowledge or facts about the columns if possible. Determine an appropriate name for this new column and explain the criteria for the new column values, including the rationale behind why certain values come before others and what world knowledge is considered for this purpose. Avoid alphabetical sorting and prioritize context and semantic relationships. Provide the new column name and its values. Also explain the mapping from the two original column values (col1_value, col2_value -> new_col_value) to the new value. For simplicity, provide the explanation on the first line, second line should be the new column name, third should be a dictionary with keys as new column names and values as the original column values to map this new column value to. Then after that, explain the reasonings."
    prompt2_modified = f"""Given two columns, '{column1}' with values {values1} and '{column2}' with values {values2}, create a new column based on the semantic relationships between these columns. Consider all the world knowledge or facts about the columns if possible. Determine an appropriate name for this new column and explain the criteria for the new column values, including the rationale behind why certain values come before others and what world knowledge is considered for this purpose. Avoid alphabetical sorting and prioritize context and semantic relationships. Provide the new column name and its values. Also, explain the mapping from the two original column values (col1_value, col2_value -> new_col_value) to the new value.

For simplicity, provide the explanation on the first line, the second line should be the new column name, the third should be a dictionary with keys as new column names and values as the original column values to map this new column value to. Then, after that, explain the reasonings."""
    response = openai.ChatCompletion.create(
      model="gpt-3.5-turbo",
      messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt2_modified}
        ],
      max_tokens=1000,
      n=1,
      stop=None,
      temperature=0.7
  )

    result = response.choices[0].message['content']
    # lines = result.split('\n')
    print(result)


data = {
    "Expedition Name": [
        "Deep Sea Exploration", "Coral Reef Survey", "Arctic Ocean Expedition",
        "Mangrove Swamp Study", "Open Ocean Dive", "Kelp Forest Research",
        "Underwater Volcano Expedition", "Seagrass Bed Investigation"
    ],
    "Marine Species": [
        "Giant Squid", "Coral", "Arctic Cod", "Mangrove Snapper", "Blue Whale",
        "Kelp Bass", "Hydrothermal Vent Worm", "Seahorse"
    ],
    "Habitat Depth (meters)": [
        3000, 20, 50, 5, 500, 30, 2500, 10
    ],
    "Conservation Status": [
        "Least Concern", "Endangered", "Near Threatened", "Vulnerable",
        "Endangered", "Least Concern", "Data Deficient", "Least Concern"
    ]
}

data2 = {
    "Exhibition Name": [
        "Renaissance Art", "Modern Abstract", "Impressionist Era", "Baroque Masterpieces",
        "Contemporary Vision", "Surrealist Dreams", "Renaissance Revival", "Abstract Revolution",
        "Impressionist Insights", "Baroque Wonders", "Modern Marvels", "Surrealist Fantasies"
    ],
    "Art Style": [
        "Renaissance", "Abstract", "Impressionism", "Baroque",
        "Contemporary", "Surrealism", "Renaissance", "Abstract",
        "Impressionism", "Baroque", "Contemporary", "Surrealism"
    ],
    "City": [
        "Florence", "New York", "Paris", "Rome", "Berlin", "Madrid",
        "Florence", "Los Angeles", "Paris", "Rome", "Chicago", "Madrid"
    ],
    "Year": [
        2020, 2018, 2019, 2021, 2017, 2018, 2022, 2019, 2020, 2021, 2016, 2017
    ],
    "Impact Level": [
        "High", "Medium", "High", "High", "Medium", "Low", "High", "Medium", "High", "High", "Medium", "Low"
    ]
}

df = pd.DataFrame(data)
df2 = pd.DataFrame(data2)
# Example usage
columns = df.columns.tolist()
columns2 = df2.columns.tolist()
print("Columns (Marine):", columns)
print("Columns (Renaissance)", columns2)

Columns (Marine): ['Expedition Name', 'Marine Species', 'Habitat Depth (meters)', 'Conservation Status']
Columns (Renaissance) ['Exhibition Name', 'Art Style', 'City', 'Year', 'Impact Level']

In [ ]:
suitable_columns = get_multiple_columns_suggestions(columns)
print("Suitable columns for semantic sorting (Marine):", suitable_columns)
print('\n\n')
suitable_columns2 = get_multiple_columns_suggestions(columns2)
print("Suitable columns for semantic sorting (Renaissance):", suitable_columns2)

Suitable columns for semantic sorting (Marine): 1. ['Marine Species', 'Conservation Status']: These two columns can be used together for semantic sorting as the conservation status of a marine species is directly related to the specific species itself. By sorting based on marine species and their corresponding conservation status, users can easily identify which species are endangered, threatened, or of least concern.

2. ['Expedition Name', 'Habitat Depth (meters)']: Semantic sorting can be done based on the expedition name and the habitat depth recorded during that expedition. This allows users to organize the data chronologically based on the expeditions conducted and the depths at which marine species were observed.

3. ['Marine Species', 'Habitat Depth (meters)']: Sorting based on marine species and habitat depth can provide insights into the distribution of species across different depths in the ocean. Users can explore how different species are distributed based on their habitat preferences.

4. ['Habitat Depth (meters)', 'Conservation Status']: Semantic sorting using habitat depth and conservation status can help identify any patterns or relationships between the depth at which marine species are found and their conservation status. This can be useful for understanding the impact of habitat depth on the conservation status of species.

5. ['Expedition Name', 'Marine Species', 'Habitat Depth (meters)', 'Conservation Status']: Sorting based on a combination of expedition name, marine species, habitat depth, and conservation status can provide a comprehensive view of the dataset. Users can explore the data in a structured manner that considers the expedition context, specific species observed, habitat depth, and conservation status all together.



Suitable columns for semantic sorting (Renaissance): 1. ['Art Style', 'Exhibition Name']: The 'Art Style' column can be used to categorize and group similar types of art together, while the 'Exhibition Name' column can provide additional context to further sort the data based on the specific exhibitions related to each art style.

2. ['City', 'Year']: The 'City' column can be used to group exhibitions based on their location, while the 'Year' column can provide a chronological order within each city, allowing for sorting based on both location and time.

3. ['Art Style', 'Impact Level']: The 'Art Style' column can categorize different types of art, while the 'Impact Level' column can provide a measure of the significance or influence of each art style, allowing for sorting based on both style and impact.

4. ['City', 'Art Style']: The 'City' column can group exhibitions based on their location, while the 'Art Style' column can further categorize the art within each city, allowing for sorting based on both location and artistic content.

5. ['Year', 'Impact Level']: The 'Year' column can provide a chronological order of exhibitions, while the 'Impact Level' column can indicate the level of influence or importance of each exhibition, allowing for sorting based on both time and impact.

In [ ]:
create_and_sort_new_column(df, "Marine Species", "Conservation Status") # considered marine species and their cons status and gave a new column conserv category with values critical, concern, etc

The new column will be named "Conservation Category" with values ['Critical', 'Concern', 'Stable', 'Data Deficient'].

```
{
    'Critical': ['Endangered', 'Vulnerable'],
    'Concern': ['Near Threatened'],
    'Stable': ['Least Concern'],
    'Data Deficient': ['Data Deficient']
}
```

Reasoning:
- **Critical**: This category includes marine species that are at significant risk of extinction and require immediate attention. Both 'Endangered' and 'Vulnerable' species fall into this category as they are facing serious threats to their survival.
- **Concern**: Species classified as 'Near Threatened' are not currently in danger of extinction but are close to meeting the criteria for Vulnerable status. Placing them in the 'Concern' category emphasizes the need for monitoring and conservation efforts.
- **Stable**: 'Least Concern' species are not currently at risk of extinction. They are considered to have stable populations and are not facing immediate threats requiring urgent action.
- **Data Deficient**: This category is for species for which there is insufficient information to assess their conservation status accurately. These species require further research and data collection to determine their level of threat.

By mapping the original 'Conservation Status' values to the new 'Conservation Category' values based on the level of threat and urgency of conservation actions required, we can better categorize and prioritize conservation efforts for different marine species.

In [ ]:
create_and_sort_new_column(df, "Marine Species", "Conservation Status") # with prompt2_modified2

Semantic Conservation Status
{'Conservation Level': {'Least Concern': 'Low Concern', 'Endangered': 'High Concern', 'Near Threatened': 'Moderate Concern', 'Vulnerable': 'High Concern', 'Data Deficient': 'Unknown Concern'}}

The new column 'Semantic Conservation Status' is based on the semantic relationships between the marine species and their conservation status. The values in this new column reflect the level of concern for the conservation status of each marine species. The mapping is as follows:

- 'Giant Squid' & 'Coral' -> 'Low Concern': Giant Squid and Coral are considered to have a relatively low level of concern for their conservation status.
- 'Arctic Cod' & 'Kelp Bass' -> 'Moderate Concern': Arctic Cod and Kelp Bass are in a state of moderate concern for their conservation status.
- 'Mangrove Snapper' -> 'High Concern': Mangrove Snapper is considered to have a high level of concern for its conservation status.
- 'Blue Whale' & 'Hydrothermal Vent Worm' -> 'Unknown Concern': Blue Whale and Hydrothermal Vent Worm have a conservation status that is currently data deficient, leading to an unknown level of concern.
- 'Seahorse' -> 'High Concern': Seahorse is classified as having a high level of concern for its conservation status due to various threats it faces in the wild.

In [ ]:
create_and_sort_new_column(df, "Marine Species", "Conservation Status") # with prompt2_modified

**New Column Name: Conservation Relationship**

**Value Hierarchy:**
1. **Critical Conservation Concern**: Represents marine species that are at the highest risk and require immediate attention due to being endangered or critically endangered.
2. **Conservation Priority**: Indicates species that are vulnerable or near threatened, highlighting the importance of conservation efforts to prevent further decline.
3. **Stable Population**: Denotes species categorized as least concern, indicating a healthy population status without immediate conservation concerns.
4. **Data Deficient**: Signifies species for which conservation status is unknown or insufficiently studied, requiring further research to determine appropriate conservation measures.

**Mapping Logic:**
- **Giant Squid** with **Endangered**: Mapping to **Critical Conservation Concern** as an endangered species requiring urgent conservation action.
- **Coral** with **Near Threatened**: Mapping to **Conservation Priority** to emphasize the need for proactive conservation efforts.
- **Arctic Cod** with **Least Concern**: Mapping to **Stable Population** as a species with a healthy population status.
- **Mangrove Snapper** with **Vulnerable**: Mapping to **Conservation Priority** due to its vulnerable status warranting conservation attention.
- **Blue Whale** with **Endangered**: Mapping to **Critical Conservation Concern** as an iconic species at high risk.
- **Kelp Bass** with **Least Concern**: Mapping to **Stable Population** indicating a healthy population status.
- **Hydrothermal Vent Worm** with **Data Deficient**: Mapping to **Data Deficient** as more information is needed for conservation assessment.
- **Seahorse** with **Near Threatened**: Mapping to **Conservation Priority** to highlight the importance of conservation efforts for this species.

In [ ]:
create_and_sort_new_column(df, "Marine Species", "Habitat Depth (meters)")

The new column will be named 'Depth Classification'.

Here is the mapping from the original columns to the new column:

{
    'Shallow': [5, 10, 20, 30],
    'Mid-Range': [50, 500],
    'Deep': [2500, 3000]
}

Reasoning:
- 'Shallow' category includes depths from 5 to 30 meters. These depths are relatively close to the surface and are typically associated with species like 'Coral' and 'Seahorse' that are commonly found in shallow waters.
- 'Mid-Range' category includes depths of 50 and 500 meters. These depths are deeper than shallow waters but not as deep as the ocean floor. Species like 'Arctic Cod' and 'Kelp Bass' are often found in these mid-range depths.
- 'Deep' category includes depths of 2500 and 3000 meters. These depths are considered deep sea zones where species like 'Giant Squid' and 'Hydrothermal Vent Worm' are known to inhabit. These species are adapted to the extreme conditions of deep ocean environments.

In [ ]:
create_and_sort_new_column(df2, "Art Style", "Exhibition Name")

**New Column Name:** Art Movement

**Mapping:**
{
    'Renaissance Art': 'Classical',
    'Modern Abstract': 'Avant-Garde',
    'Impressionist Era': 'Traditional',
    'Baroque Masterpieces': 'Classical',
    'Contemporary Vision': 'Avant-Garde',
    'Surrealist Dreams': 'Avant-Garde',
    'Renaissance Revival': 'Neo-Classical',
    'Abstract Revolution': 'Avant-Garde',
    'Impressionist Insights': 'Traditional',
    'Baroque Wonders': 'Neo-Classical',
    'Modern Marvels': 'Avant-Garde',
    'Surrealist Fantasies': 'Avant-Garde'
}

**Reasoning:**
- **Classical**: Columns 'Renaissance Art' and 'Baroque Masterpieces' are categorized as Classical due to their historical context and traditional art styles associated with these periods.
- **Avant-Garde**: Columns 'Modern Abstract', 'Contemporary Vision', 'Surrealist Dreams', 'Abstract Revolution', 'Modern Marvels', and 'Surrealist Fantasies' are considered Avant-Garde for their innovative and experimental approaches to art.
- **Traditional**: Columns 'Impressionist Era' and 'Impressionist Insights' are labeled as Traditional to reflect the foundational nature of Impressionism in the art world.
- **Neo-Classical**: Columns 'Renaissance Revival' and 'Baroque Wonders' are placed under Neo-Classical as they represent a modern revival or reinterpretation of Classical art styles with contemporary influences.

In [ ]:
create_and_sort_new_column(df2, "Art Style", "Exhibition Name") # prompt2_modified

The new column name is "Art Movement"
{
    'Renaissance Art': 'Classical',
    'Modern Abstract': 'Modern',
    'Impressionist Era': 'Classic',
    'Baroque Masterpieces': 'Classical',
    'Contemporary Vision': 'Modern',
    'Surrealist Dreams': 'Modern',
    'Renaissance Revival': 'Modern',
    'Abstract Revolution': 'Modern',
    'Impressionist Insights': 'Classic',
    'Baroque Wonders': 'Classical',
    'Modern Marvels': 'Modern',
    'Surrealist Fantasies': 'Modern'
}

Explanation:
The new column "Art Movement" categorizes the art styles and exhibition names into either "Classic" or "Modern" based on the historical context and characteristics associated with the art styles.

- 'Renaissance Art', 'Baroque Masterpieces', and 'Baroque Wonders' are categorized as "Classical" due to their association with historical periods known for detailed realism, grandeur, and religious themes.
- 'Impressionist Era' and 'Impressionist Insights' are classified as "Classic" since Impressionism represents a significant art movement in the late 19th century known for capturing light and fleeting moments.
- 'Modern Abstract', 'Contemporary Vision', 'Surrealist Dreams', 'Renaissance Revival', 'Abstract Revolution', 'Modern Marvels', and 'Surrealist Fantasies' are grouped as "Modern" reflecting contemporary approaches, experimental techniques, and unconventional subject matters.

The categorization considers the traditional versus contemporary aspects of art movements and aligns them with the historical context and characteristics of the specific art styles and exhibition names.

In [ ]:
create_and_sort_new_column(df2, "Art Style", "Impact Level")

New Column Name: Artistic Influence

Mapping:
{
    'Renaissance': 'High',
    'Baroque': 'High',
    'Impressionism': 'Medium',
    'Abstract': 'Medium',
    'Surrealism': 'Low',
    'Contemporary': 'Low'
}

Reasoning:
- The new column 'Artistic Influence' is based on the historical impact and influence of each art style on subsequent art movements.
- Renaissance and Baroque are considered to have a 'High' influence due to their significant impact on the art world, setting standards and influencing generations of artists.
- Impressionism and Abstract art have a 'Medium' influence as they introduced new techniques and ideas that had a substantial impact on art but did not revolutionize the entire art world like Renaissance and Baroque.
- Surrealism and Contemporary art are categorized as 'Low' influence as they are considered more niche movements that did not have as widespread impact as the other styles.
- The mapping reflects the continuum of influence from high to low based on the perceived historical significance and influence of each art style.

In [ ]:
create_and_sort_new_column(df2, "Art Style", "Impact Level")  #p prompt2_modified

Artistic Influence Level
{
    'High Renaissance': ('Renaissance', 'High'),
    'Medium Baroque': ('Baroque', 'Medium'),
    'Low Abstract': ('Abstract', 'Low'),
    'Low Impressionism': ('Impressionism', 'Low'),
    'Medium Contemporary': ('Contemporary', 'Medium'),
    'High Surrealism': ('Surrealism', 'High')
}

The new column name is 'Artistic Influence Level'. The values in this new column are determined based on the semantic relationships between the 'Art Style' and 'Impact Level' columns.

1. 'High Renaissance': This value indicates a significant artistic influence level, as seen during the Renaissance period, known for its high impact on art history and cultural development. The 'High' impact level further emphasizes the profound influence of this art style.

2. 'Medium Baroque': The Baroque art style is known for its grandeur and dramatic impact on art and architecture. The 'Medium' impact level signifies a moderate level of influence compared to the Renaissance period.

3. 'Low Abstract': Abstract art, characterized by non-representational forms and shapes, is considered to have a lower direct influence compared to more traditional styles. The 'Low' impact level reflects this lesser impact on subsequent art movements.

4. 'Low Impressionism': Impressionism, with its focus on capturing light and momentary impressions, had a significant impact on modern art but is categorized here as having a lower influence compared to other styles.

5. 'Medium Contemporary': Contemporary art encompasses a wide range of styles and movements reflecting the present time. The 'Medium' impact level indicates a varied influence level depending on the specific contemporary style.

6. 'High Surrealism': Surrealism, known for its dream-like and subconscious imagery, had a profound impact on art and literature. The 'High' impact level highlights the lasting influence of this style on the art world.

In [ ]:
create_and_sort_new_column(df2, "Art Style", "City")

Explanation:
The new column will capture the relationship between the 'Art Style' and 'City' columns by considering the historical and cultural context of each art style in relation to the cities where they flourished or are commonly associated with. The idea is to create a meaningful connection between the art style and the city based on historical significance and artistic movements.

New Column Name:
Artistic Influence

Mapping Dictionary:
{
    'Renaissance_Florence': ['Renaissance', 'Florence'],
    'Abstract_New York': ['Abstract', 'New York'],
    'Impressionism_Paris': ['Impressionism', 'Paris'],
    'Baroque_Rome': ['Baroque', 'Rome'],
    'Contemporary_Berlin': ['Contemporary', 'Berlin'],
    'Surrealism_Madrid': ['Surrealism', 'Madrid'],
    'Surrealism_Los Angeles': ['Surrealism', 'Los Angeles'],
    'Abstract_Los Angeles': ['Abstract', 'Los Angeles'],
    'Impressionism_Chicago': ['Impressionism', 'Chicago']
}

Reasoning:
1. The Renaissance art style is closely associated with Florence due to the flourishing of art, architecture, and culture during that period in the city.
2. Abstract art has strong ties to New York, known for being a hub of modern art movements and avant-garde artists.
3. Impressionism originated in Paris and is synonymous with the vibrant art scene of the city during the 19th century.
4. Baroque art finds its roots in Rome, where the style was prominent in architecture, sculpture, and painting.
5. Contemporary art is often linked to Berlin, a city known for its diverse and cutting-edge art scene.
6. Surrealism has connections to Madrid, where artists like Salvador Dalí and Joan Miró were key figures in the surrealist movement.
7. Surrealism is also associated with Los Angeles, particularly in the realm of pop surrealism and contemporary art.
8. Abstract art is connected to Los Angeles due to its influence in the city's modern art landscape.
9. Impressionism is linked to Chicago, where the style gained popularity and left a mark on the city's art history.

In [ ]:
data3 = {
    "Car Model": [
        "Toyota Corolla", "Honda Civic", "Ford F-Series", "Chevrolet Silverado", "Volkswagen Golf",
        "Toyota Camry", "BMW 3 Series", "Mercedes-Benz C-Class", "Audi A4", "Hyundai Elantra"
    ],
    "Manufacturer": [
        "Toyota", "Honda", "Ford", "Chevrolet", "Volkswagen",
        "Toyota", "BMW", "Mercedes-Benz", "Audi", "Hyundai"
    ],
    "Region": [
        "North America", "North America", "North America", "North America", "Europe",
        "North America", "Europe", "Europe", "Europe", "Asia"
    ],
    "Year Released": [
        2019, 2020, 2018, 2017, 2018,
        2020, 2019, 2017, 2018, 2019
    ],
    "Average Price": [
        "$20,000", "$22,000", "$30,000", "$35,000", "$25,000",
        "$23,000", "$40,000", "$45,000", "$38,000", "$21,000"
    ],
    "Sales Volume": [
        300000, 250000, 200000, 180000, 150000,
        280000, 220000, 190000, 160000, 210000
    ]
}

In [ ]:
df3 = pd.DataFrame(data3)
columns3 = df3.columns.tolist()
suitable_columns3 = get_multiple_columns_suggestions(columns3)
print("Suitable columns for semantic sorting (Marine):", suitable_columns3)

Suitable columns for semantic sorting (Marine): 1. ['Manufacturer', 'Region']
Explanation: The Manufacturer and Region columns have a hierarchical relationship, with manufacturers typically associated with specific regions. This relationship can be used to sort the dataset based on the manufacturing location.

2. ['Region', 'Sales Volume']
Explanation: The Region and Sales Volume columns can be used together for sorting based on the sales performance in different regions. This relationship allows for sorting based on regional sales data.

3. ['Car Model', 'Manufacturer']
Explanation: The Car Model and Manufacturer columns have a categorical relationship, as specific car models are typically associated with specific manufacturers. This relationship can be used for sorting based on the manufacturer's car models.

4. ['Year Released', 'Average Price']
Explanation: The Year Released and Average Price columns can be used together for sorting based on the average price of cars released in different years. This relationship allows for sorting based on pricing trends over time.

5. ['Manufacturer', 'Sales Volume']
Explanation: The Manufacturer and Sales Volume columns can be used together for sorting based on the sales performance of different manufacturers. This relationship allows for sorting based on manufacturers' sales volumes.

In [ ]:
create_and_sort_new_column(df3, "Manufacturer", "Region")

The new column name is 'Global Influence'.
{
    'Global Influence': {
        ('Toyota', 'North America'): 'North America',
        ('Toyota', 'Europe'): 'Europe',
        ('Toyota', 'Asia'): 'Asia',
        ('Honda', 'North America'): 'North America',
        ('Honda', 'Europe'): 'Europe',
        ('Honda', 'Asia'): 'Asia',
        ('Ford', 'North America'): 'North America',
        ('Ford', 'Europe'): 'Europe',
        ('Ford', 'Asia'): 'Asia',
        ('Chevrolet', 'North America'): 'North America',
        ('Chevrolet', 'Europe'): 'Europe',
        ('Chevrolet', 'Asia'): 'Asia',
        ('Volkswagen', 'North America'): 'Europe',
        ('Volkswagen', 'Europe'): 'Europe',
        ('Volkswagen', 'Asia'): 'Asia',
        ('BMW', 'North America'): 'Europe',
        ('BMW', 'Europe'): 'Europe',
        ('BMW', 'Asia'): 'Asia',
        ('Mercedes-Benz', 'North America'): 'Europe',
        ('Mercedes-Benz', 'Europe'): 'Europe',
        ('Mercedes-Benz', 'Asia'): 'Asia',
        ('Audi', 'North America'): 'Europe',
        ('Audi', 'Europe'): 'Europe',
        ('Audi', 'Asia'): 'Asia',
        ('Hyundai', 'North America'): 'North America',
        ('Hyundai', 'Europe'): 'Europe',
        ('Hyundai', 'Asia'): 'Asia'
    }
}

Reasoning:
1. The assignment of values in the 'Global Influence' column is based on the headquarters or primary market of each manufacturer.
2. Manufacturers like Toyota, Honda, Ford, and Chevrolet have strong associations with North America due to their historical presence and significant market share in the region.
3. European manufacturers such as Volkswagen, BMW, Mercedes-Benz, and Audi are primarily associated with Europe due to their origins and strong market presence in the region.
4. Hyundai, while being an Asian manufacturer, has expanded its global presence and is now associated with both Asia and North America, reflecting its diverse market reach.

## Semantic sorting using mutliple columns from multiple tables

#### Numeric cols (ids)

In [ ]:
import pandas as pd

In [ ]:
def identify_joinable_datasets(datasets):

    '''
      here, I only give dataset names and its columns as input and try if gpt is able to give suggestions
    '''

    prompt = f'Given the datasets: {datasets}, identify which datasets can be joined based on semantic relationships. Explain the join keys and why these datasets can be joined. Provide as many join suggestions as possible with the most probable first.'

    response = openai.ChatCompletion.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )

    result = response['choices'][0]['message']['content'].strip()
    return result

def identify_columns_for_sorting(columns):
    prompt = f'Given the columns {columns}, which columns can be used together to do semantic sorting of the dataset? Focus on columns that have hierarchical, contextual, or categorical relationships and if possible try to ignore alphabetical sorting. Provide the answer in the format [column1, column2]. Explanation: reasoning about why these columns can be used together to do semantic sorting. Give as many suggestions as possible with most probable first.'

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )

    result = response['choices'][0]['message']['content'].strip()
    return result

# these datasets have similar column names, and join columns are clearly visible
data1 = {
    "Employee_ID": [1, 2, 3, 4, 5, 6],
    "Name": ["Fiona Black", "Charlie Lee", "Evan Green", "Bob Johnson", "Dana White", "Alice Smith"],
    "Department": ["Engineering", "Marketing", "Sales", "Engineering", "HR", "Engineering"],
    "State": ["Ohio", "New York", "Illinois", "California", "Florida", "Texas"]
}

data2 = {
    "Employee_ID": [1, 2, 3, 4, 5, 6],
    "Job_Level": ["Junior", "Junior", "Associate", "Associate", "Senior", "Senior"],
    "Salary": ["$65,000", "$70,000", "$85,000", "$90,000", "$115,000", "$120,000"]
}

data3 = {
    "Department_ID": [1, 2, 3, 4],
    "Department": ["Engineering", "Marketing", "Sales", "HR"],
    "Manager": ["Alice Smith", "Bob Johnson", "Dana White", "Charlie Lee"]
}

datasets = [
    {"name": "Employee Information", "columns": ["Employee_ID", "Name", "Department", "State"]},
    {"name": "Employee Roles and Salaries", "columns": ["Employee_ID", "Job_Level", "Salary"]},
    {"name": "Department Information", "columns": ["Department_ID", "Department", "Manager"]}
]

joinable_datasets = identify_joinable_datasets(datasets)
print("Joinable Datasets:")
print(joinable_datasets)

Joinable Datasets:
The datasets can be joined based on common columns (also called join keys) that represent the same entity across different datasets. Here are the datasets and possible joins:

1. **Employee Information** and **Employee Roles and Salaries**

   **Join Key:**
   - `Employee_ID` (common in both datasets)

   **Explanation:**
   - Both the "Employee Information" and "Employee Roles and Salaries" datasets contain an `Employee_ID` column. This indicates that each record in both datasets corresponds to individual employees. By joining these datasets on `Employee_ID`, you can combine employee details (like name and department) with their job roles and salaries.

   `SQL Join Example:`
   ```sql
   SELECT a.Employee_ID, a.Name, a.Department, a.State, b.Job_Level, b.Salary
   FROM Employee_Information a
   JOIN Employee_Roles_and_Salaries b
   ON a.Employee_ID = b.Employee_ID;
   ```

2. **Employee Information** and **Department Information**

   **Join Key:**
   - `Department` (in "Employee Information") and `Department` (in "Department Information")

   **Explanation:**
   - The "Employee Information" dataset includes a `Department` column that describes which department an employee belongs to. The "Department Information" dataset has a `Department` column that provides additional details about each department, such as the department manager. By joining on the `Department` column, you can enrich employee records with information about their respective departments.

   `SQL Join Example:`
   ```sql
   SELECT a.Employee_ID, a.Name, a.Department, a.State, b.Department_ID, b.Manager
   FROM Employee_Information a
   JOIN Department_Information b
   ON a.Department = b.Department;
   ```

3. **Department Information** and **Employee Roles and Salaries**

   **Possible Join: (Indirect Relationship)**

   **Join Key:**
   - Not a direct join, but potentially by joining through "Employee Information" using the `Department`.

   **Explanation:**
   - There is no direct join key connecting "Employee Roles and Salaries" and "Department Information". However, you can achieve an indirect relationship by first joining "Employee Information" with both datasets and using that intermediate result.

   `SQL Join Example:`
   ```sql
   SELECT e.Employee_ID, e.Name, e.Department, e.State, r.Job_Level, r.Salary, d.Department_ID, d.Manager
   FROM Employee_Information e
   JOIN Employee_Roles_and_Salaries r
   ON e.Employee_ID = r.Employee_ID
   JOIN Department_Information d
   ON e.Department = d.Department;
   ```

4. **Cross Join Consideration:**

   If for some reason, none of the direct join keys are suitable (unlikely except for special cases), you could consider a cross join; however, this results in a Cartesian product, which is typically not desirable due to its large size and unrelated nature of the resulting data:

   ```sql
   SELECT *
   FROM Employee_Information a
   CROSS JOIN Employee_Roles_and_Salaries b;
   ```

In conclusion, the most probable and meaningful join suggestions would be:

1. Joining "Employee Information" with "Employee Roles and Salaries" using `Employee_ID`.
2. Joining "Employee Information" with "Department Information" using `Department`.
3. An indirect join of all three datasets by using the `Employee Information` dataset as an intermediary to connect the other two datasets.

In [ ]:
# merging tables and generating sort suggestions
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

df_joined = pd.merge(df1, df2, on="Employee_ID")

# Identify columns for semantic sorting
columns = df_joined.columns.tolist()
columns_for_sorting = identify_columns_for_sorting(columns)
print("Columns for Semantic Sorting:")
print(columns_for_sorting)

Columns for Semantic Sorting:
1. ['Department', 'Job_Level']: These columns can be used together for semantic sorting as they represent hierarchical relationships within the organization. Employees within the same department are likely to have similar job levels, allowing for a meaningful sorting based on job hierarchy within different departments.

2. ['State', 'Department']: Sorting by state and department can provide a contextual sorting that groups employees based on their geographic location as well as their department within the organization.

3. ['Job_Level', 'Salary']: These columns represent a hierarchical relationship as employees with higher job levels typically have higher salaries. Sorting based on job level and then by salary can help in identifying salary discrepancies or patterns within each job level.

4. ['Department', 'State']: Sorting by department and state can provide a hierarchical and contextual sorting that groups employees by their department first and then by their location within that department.

5. ['State', 'Salary']: This combination can provide a contextual sorting based on the employees' geographic location and their salary levels. It can be useful for identifying regional salary trends or disparities.

By using these column combinations for semantic sorting, you can effectively organize the dataset in a way that is meaningful and relevant to the organizational structure and categorical relationships represented in the data.

In [ ]:
columns

['Employee_ID', 'Name', 'Department', 'State', 'Job_Level', 'Salary']

In [ ]:
department = list(df_joined['Department'].unique())
state = list(df_joined['State'].unique())
job_level = list(df_joined['Job_Level'].unique())

In [ ]:
dep_state = semantic_sort_multiple_column2("Department", department, "State", state)

In [ ]:
final_dep_state = dep_state.split("\n\n")
for suggestion in final_dep_state:
  print(suggestion)
  print("\n")

To generate all unique combinations of values from the 'Department' and 'State' columns, we can pair each unique Department value with each unique State value. Then, to provide a semantic sorting of these combined values, we can consider the following criteria:


1. Geographic Proximity: States that are geographically close to each other may be considered more closely related than those that are far apart.
2. Industry Affiliation: Certain departments may be more commonly associated with specific states due to industry clusters or historical reasons.
3. Regional Preferences: Some departments may have a higher presence or significance in certain regions, influencing the perceived relationship between the department and state.


Based on these criteria, we can generate and semantically sort the combined values as follows:


1. Engineering in California
2. Engineering in Texas
3. Marketing in California
4. Marketing in Texas
5. Sales in California
6. Sales in Texas
7. Engineering in Florida
8. Marketing in Florida
9. Sales in Florida
10. Engineering in New York
11. Marketing in New York
12. Sales in New York
13. Engineering in Ohio
14. Marketing in Ohio
15. Sales in Ohio
16. HR in California
17. HR in Texas
18. HR in Florida
19. HR in New York
20. HR in Ohio
21. HR in Illinois


These combinations are sorted based on the considerations mentioned above, reflecting potential real-world relationships between departments and states.

In [ ]:
dep_job = semantic_sort_multiple_column("Department", department, "job_level", job_level)

In [ ]:
final_dep_job = dep_job.split("\n\n")
for suggestion in final_dep_job:
  print(suggestion)
  print("\n")

For the combined column of Department and job_level, a semantic sorting could be done based on the hierarchy and typical progression within organizations. Here is the sorted list:


1. Engineering - Junior
2. Engineering - Associate
3. Engineering - Senior
4. Marketing - Junior
5. Marketing - Associate
6. Marketing - Senior
7. Sales - Junior
8. Sales - Associate
9. Sales - Senior
10. HR - Junior
11. HR - Associate
12. HR - Senior


The rationale behind this sorting is based on the typical organizational structure and career progression in many companies. Generally, employees start at the Junior level in a specific department and then progress to the Associate and Senior levels as they gain more experience and expertise.


Additionally, certain departments may have different career progression paths or job level structures. For example, in some organizations, technical roles in Engineering may have more defined levels compared to roles in Marketing or HR.


This sorting takes into account the natural progression of roles within departments and reflects the typical career advancement path in a professional setting.

In [ ]:
data1 = {
    "Emp_ID": [1, 2, 3, 4, 5, 6],
    "FullName": ["Fiona Black", "Charlie Lee", "Evan Green", "Bob Johnson", "Dana White", "Alice Smith"],
    "D_Col": ["Eng", "Mkt", "Sales", "Eng", "HR", "Eng"], # Dept changed to D_col
    "Location": ["OH", "NY", "IL", "CA", "FL", "TX"]
}

data2 = {
    "EmployeeID": [1, 2, 3, 4, 5, 6],
    "JobTitle": ["Junior", "Junior", "Associate", "Associate", "Senior", "Senior"],
    "Pay": [65000, 70000, 85000, 90000, 115000, 120000]
}

data3 = {
    "Dept_ID": [1, 2, 3, 4],
    "Department": ["Engineering", "Marketing", "Sales", "HumanRes"],
    "Head": ["Alice Smith", "Bob Johnson", "Dana White", "Charlie Lee"]
}

datasets = [
    {"name": "Employee Info", "columns": ["Emp_ID", "FullName", "d_col", "Location"]},
    {"name": "Roles and Salaries", "columns": ["EmployeeID", "JobTitle", "Pay"]},
    {"name": "Department Info", "columns": ["Dept_ID", "Department", "Head"]}
]

In [ ]:
joinable_datasets = identify_joinable_datasets(datasets)
print("Joinable Datasets:")
print(joinable_datasets)

Joinable Datasets:
To identify which datasets can be joined based on semantic relationships, it's crucial to examine the column names and their likely meanings. Here are the datasets provided:

1. **Employee Info**: Columns - ['Emp_ID', 'FullName', 'd_col', 'Location']
2. **Roles and Salaries**: Columns - ['EmployeeID', 'JobTitle', 'Pay']
3. **Department Info**: Columns - ['Dept_ID', 'Department', 'Head']

### Most Probable Joins

1. **Employee Info ↔ Roles and Salaries**

   **Join Keys:**
   - `Employee Info[Emp_ID]` = `Roles and Salaries[EmployeeID]`

   **Explanation:**
   - `Emp_ID` in "Employee Info" and `EmployeeID` in "Roles and Salaries" likely represent the same entity, which is the unique identifier for an employee. This allows for a natural join between these datasets to enrich the employee information with their respective roles and salaries.

2. **Employee Info ↔ Department Info**

   **Join Keys:**
   - `Employee Info[d_col]` = `Department Info[Dept_ID]`

   **Explanation:**
   - Although `d_col` is ambiguously named, it likely stands for a column related to the department, potentially `Department Column`. If `d_col` indeed represents the `Dept_ID`, this allows a join between "Employee Info" and "Department Info" to link employees to their departments.

### Joining Scenarios

1. **Join Scenario 1: Employee Info and Roles and Salaries**
   ```sql
   SELECT *
   FROM Employee_Info EI
   JOIN Roles_and_Salaries RS
   ON EI.Emp_ID = RS.EmployeeID;
   ```

2. **Join Scenario 2: Employee Info and Department Info**
   ```sql
   SELECT *
   FROM Employee_Info EI
   JOIN Department_Info DI
   ON EI.d_col = DI.Dept_ID;
   ```

3. **Combined Join Scenario: Employee Info, Roles and Salaries, and Department Info**
   ```sql
   SELECT *
   FROM Employee_Info EI
   JOIN Roles_and_Salaries RS
   ON EI.Emp_ID = RS.EmployeeID
   JOIN Department_Info DI
   ON EI.d_col = DI.Dept_ID;
   ```

### Less Probable Joins

Given the structure and names of the columns in the datasets, less probable joins could involve attempting to join department information directly with roles and salaries. There are no obvious keys to join "Roles and Salaries" directly to "Department Info" without intermediary data.

### Summary

The two most probable joins are:

1. **Employee Info** and **Roles and Salaries** using employee IDs.
2. **Employee Info** and **Department Info** if `d_col` indeed corresponds to `Dept_ID`.

These joins help in constructing a comprehensive view of the employees, their roles, salaries, and department affiliations.

## Sampling data

In [ ]:
def identify_joinable_datasets_with_samples(samples, mod):
    prompt = f'Given the following samples of rows from different datasets, identify which datasets can be joined based on the content of the rows. Explain the join keys and why these datasets can be joined. Provide as many join suggestions as possible with the most probable first.\n\nSamples:\n{samples}'

    response = openai.ChatCompletion.create(
        model=f"gpt-{mod}",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )

    result = response['choices'][0]['message']['content'].strip()
    return result

In [ ]:
data1 = {
    "Emp_ID": [1, 2, 3, 4, 5, 6],
    "FullName": ["Fiona Black", "Charlie Lee", "Evan Green", "Bob Johnson", "Dana White", "Alice Smith"],
    "random": ["Eng", "Mkt", "Sales", "Eng", "HR", "Eng"], # kept random to see if gpt can relate
    "Location": ["OH", "NY", "IL", "CA", "FL", "TX"]
}

data2 = {
    "EmployeeID": [1, 2, 3, 4, 5, 6],
    "JobTitle": ["Junior", "Junior", "Associate", "Associate", "Senior", "Senior"],
    "Pay": [65000, 70000, 85000, 90000, 115000, 120000]
}

data3 = {
    "Dept_ID": [1, 2, 3, 4],
    "Department": ["Engineering", "Marketing", "Sales", "HumanRes"],
    "Head": ["Alice Smith", "Bob Johnson", "Dana White", "Charlie Lee"]
}

datasets = [
    {"name": "Employee Info", "columns": ["Emp_ID", "FullName", "d_col", "Location"]},
    {"name": "Roles and Salaries", "columns": ["EmployeeID", "JobTitle", "Pay"]},
    {"name": "Department Info", "columns": ["Dept_ID", "Department", "Head"]}
]

In [ ]:
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)
sample1 = df1.sample(n=4, random_state=1).to_dict(orient='records')
sample2 = df2.sample(n=4, random_state=1).to_dict(orient='records')
sample3 = df3.sample(n=4, random_state=1).to_dict(orient='records')
samples = f'Dataset 1: {sample1}\nDataset 2: {sample2}\nDataset 3: {sample3}'

In [ ]:
joinable_datasets = identify_joinable_datasets_with_samples(samples, "3.5-turbo")
print("Joinable Datasets:")
print(joinable_datasets)

Joinable Datasets:
Based on the content of the rows in the provided datasets, here are the potential join suggestions:

1. Join Datasets 1 and 2:
   - Join Key: 'Emp_ID' from Dataset 1 and 'EmployeeID' from Dataset 2
   - Explanation: These datasets can be joined on the common key 'Emp_ID' and 'EmployeeID' to combine the employee information ('FullName' and 'random') with the job details ('JobTitle' and 'Pay').

2. Join Datasets 1 and 3:
   - Join Key: 'random' from Dataset 1 and 'Department' from Dataset 3
   - Explanation: These datasets can be joined by mapping the department names from Dataset 1 to the corresponding departments in Dataset 3, based on the 'random' and 'Department' values.

3. Join Datasets 2 and 3:
   - Join Key: 'EmployeeID' from Dataset 2 and 'Dept_ID' from Dataset 3
   - Explanation: These datasets can be joined based on the common key 'EmployeeID' and 'Dept_ID' to associate the job details from Dataset 2 with the department information from Dataset 3.

These are the possible join suggestions with the most probable ones listed first. Depending on the analysis needed, you can merge these datasets for a more comprehensive view of the employee, job, and department-related information.

In [ ]:
# giving only data1 and data3
samples2 = f'Dataset 1: {sample1}\nDataset 3: {sample3}'

In [ ]:
joinable_datasets = identify_joinable_datasets_with_samples(samples2, "3.5-turbo")
print("Joinable Datasets:")
print(joinable_datasets)

Joinable Datasets:
Based on the provided samples, the datasets that can be joined are Dataset 1 and Dataset 3.

Join Suggestion 1:
Join Key: 'random' in Dataset 1 and 'Department' in Dataset 3
Explanation: Both datasets have a field related to departments, i.e., 'random' in Dataset 1 represents the department where an employee works, and 'Department' in Dataset 3 represents the name of the department. By joining on these fields, you can link employee information to the respective departments they belong to.

Join Suggestion 2:
Join Key: 'FullName' in Dataset 1 and 'Head' in Dataset 3
Explanation: The 'FullName' in Dataset 1 and the 'Head' in Dataset 3 represent the names of employees who lead a department. By joining on these fields, you can establish a relationship between the employees in Dataset 1 and the heads of departments in Dataset 3.

These suggestions are based on the common attributes that provide a logical connection between the two datasets. Make sure to clean the data and handle any discrepancies in the keys before performing the join operation.

In [ ]:
# Using gpt 4o
joinable_datasets_4 = identify_joinable_datasets_with_samples(samples, "4o")
print("Joinable Datasets:")
print(joinable_datasets_4)

Joinable Datasets:
Based on the samples provided from the different datasets, here are the possible join suggestions:

### Join Suggestion 1: Dataset 1 and Dataset 2
**Join Keys:**
- `Emp_ID` from Dataset 1
- `EmployeeID` from Dataset 2

**Explanation:**
The `Emp_ID` field in Dataset 1 appears to correspond to the `EmployeeID` field in Dataset 2. Both fields uniquely identify employees and can be used to join the rows such that information about employees from Dataset 1 (e.g., FullName, Location) is combined with their job titles and pay information from Dataset 2.

Example Result:
```
[
  {'Emp_ID': 3, 'FullName': 'Evan Green', 'random': 'Sales', 'Location': 'IL', 'JobTitle': 'Associate', 'Pay': 85000},
  {'Emp_ID': 2, 'FullName': 'Charlie Lee', 'random': 'Mkt', 'Location': 'NY', 'JobTitle': 'Junior', 'Pay': 70000},
  {'Emp_ID': 5, 'FullName': 'Dana White', 'random': 'HR', 'Location': 'FL', 'JobTitle': 'Senior', 'Pay': 115000},
  {'Emp_ID': 1, 'FullName': 'Fiona Black', 'random': 'Eng', 'Location': 'OH', 'JobTitle': 'Junior', 'Pay': 65000}
]
```

### Join Suggestion 2: Dataset 1 and Dataset 3
**Join Keys:**
- `FullName` from Dataset 1
- `Head` from Dataset 3

**Explanation:**
The `FullName` field in Dataset 1 appears to correspond to the `Head` field in Dataset 3. Both fields represent names of employees and can be used to join the rows such that information about employees from Dataset 1 (e.g., Emp_ID, Location) is combined with the department they head from Dataset 3.

Example Result:
```
[
  {'Emp_ID': 2, 'FullName': 'Charlie Lee', 'random': 'Mkt', 'Location': 'NY', 'Dept_ID': 4, 'Department': 'HumanRes'},
  {'Emp_ID': 5, 'FullName': 'Dana White', 'random': 'HR', 'Location': 'FL', 'Dept_ID': 3, 'Department': 'Sales'}
]
```

### Join Suggestion 3: Dataset 2 and Dataset 3
**Potential Join:**
There might not be an obvious direct join key between Dataset 2 and Dataset 3 based solely on the given rows, but if there are additional rows or context in the full datasets, further exploration could uncover other potential join keys.

However, here is a hypothetical indirect join through Dataset 1 using employee names:
1. Join Dataset 1 and Dataset 2 using Emp_ID and EmployeeID. Use this join to create a comprehensive dataset that includes FullNames.
2. Join the result of step 1 with Dataset 3 on FullName and Head.

Example Flow:
1. Join Dataset 1 and Dataset 2:
```
[
  {'FullName': 'Evan Green', 'Location': 'IL', 'JobTitle': 'Associate', 'Pay': 85000},
  {'FullName': 'Charlie Lee', 'Location': 'NY', 'JobTitle': 'Junior', 'Pay': 70000},
  {'FullName': 'Dana White', 'Location': 'FL', 'JobTitle': 'Senior', 'Pay': 115000},
  {'FullName': 'Fiona Black', 'Location': 'OH', 'JobTitle': 'Junior', 'Pay': 65000}
]
```
2. Join the result of step 1 with Dataset 3 on FullName and Head:
```
[
  {'FullName': 'Charlie Lee', 'Location': 'NY', 'JobTitle': 'Junior', 'Pay': 70000, 'Dept_ID': 4, 'Department': 'HumanRes'},
  {'FullName': 'Dana White', 'Location': 'FL', 'JobTitle': 'Senior', 'Pay': 115000, 'Dept_ID': 3, 'Department': 'Sales'}
]
```

These join suggestions are based on common fields that apparently correspond to each other in the provided dataset samples. More robust joins would be possible with additional context or more detailed datasets.

In [ ]:
# Example datasets with random column names
data1 = {
    "PID": [101, 102, 103, 104, 105, 106],
    "P_Name": ["Laptop", "Desk Chair", "Smartphone", "Bookshelf", "Tablet", "Office Lamp"],
    "Cat_Code": ["ELC", "FUR", "ELC", "FUR", "ELC", "FUR"],
    "Loc": ["NY", "CA", "TX", "IL", "FL", "OH"]
}

data2 = {
    "SaleID": [1001, 1002, 1003, 1004, 1005, 1006],
    "Prod_ID": [101, 103, 102, 104, 106, 105],
    "S_Price": [1000, 700, 150, 200, 50, 800],
    "S_Loc": ["NY", "TX", "CA", "IL", "OH", "FL"]
}

data3 = {
    "SupplierID": [201, 202, 203, 204, 205, 206],
    "Prod_Code": ["ELC", "FUR", "ELC", "FUR", "ELC", "FUR"],
    "Sup_Name": ["Tech Supplies Co", "Furnishings Ltd", "Mobile World", "Home Comforts", "Gadget Hub", "Office Essentials"],
    "S_Location": ["New York", "California", "Texas", "Illinois", "Florida", "Ohio"]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

sample1 = df1.sample(n=4, random_state=1).to_dict(orient='records')
sample2 = df2.sample(n=4, random_state=1).to_dict(orient='records')
sample3 = df3.sample(n=4, random_state=1).to_dict(orient='records')
samples = f'Dataset 1: {sample1}\nDataset 2: {sample2}\nDataset 3: {sample3}'

joinable_datasets = identify_joinable_datasets_with_samples(samples, "3.5-turbo")
print("Joinable Datasets:")
print(joinable_datasets)

Joinable Datasets:
Based on the content of the rows provided in the datasets, here are the possible joins that can be made:

1. Join between Dataset 1 and Dataset 2:
   - Join Key: `PID` from Dataset 1 and `Prod_ID` from Dataset 2
   - Explanation: Both datasets have a common identifier for products in the form of IDs (`PID` in Dataset 1 and `Prod_ID` in Dataset 2). By joining on these keys, you can relate the product details from Dataset 1 with the sales information from Dataset 2.

2. Join between Dataset 2 and Dataset 3:
   - Join Key: `Prod_ID` from Dataset 2 and `Prod_Code` from Dataset 3
   - Explanation: Both datasets have a relationship between the products being sold and the corresponding product codes. By joining on these keys, you can connect the sales data in Dataset 2 with the supplier information in Dataset 3 based on the product codes.

3. Join between Dataset 1 and Dataset 3:
   - Join Key: `Cat_Code` from Dataset 1 and `Prod_Code` from Dataset 3
   - Explanation: Both datasets have a common category code field (`Cat_Code` in Dataset 1 and `Prod_Code` in Dataset 3) that can be used to join the product information in Dataset 1 with the supplier information in Dataset 3 based on the product categories.

These are the possible joins based on the available data and keys in the provided datasets.

In [ ]:
# using gpt 4o
joinable_datasets_2 = identify_joinable_datasets_with_samples(samples, "4o")
print("Joinable Datasets:")
print(joinable_datasets_2)

Joinable Datasets:
Based on the provided rows from the datasets, the datasets can be joined on various keys. Below are the join suggestions, starting with the most probable first:

**1. Join Dataset 1 and Dataset 2:**

- **Join Keys:** `PID` from Dataset 1 and `Prod_ID` from Dataset 2.
- **Reason:**
  - Both columns represent product IDs (`PID` and `Prod_ID`).
  - There is a clear relation indicating that sales (Dataset 2) are linked to products (Dataset 1).

**Example:**
Dataset 1 Row: `{'PID': 103, 'P_Name': 'Smartphone', 'Cat_Code': 'ELC', 'Loc': 'TX'}`
Dataset 2 Row: `{'SaleID': 1002, 'Prod_ID': 103, 'S_Price': 700, 'S_Loc': 'TX'}`

**2. Join Dataset 1 and Dataset 3:**

- **Join Keys:** `Cat_Code` from Dataset 1 and `Prod_Code` from Dataset 3.
- **Reason:**
  - Both columns represent category codes (`Cat_Code` and `Prod_Code`) that categorize products.
  - This join can indicate a relationship between products and their suppliers based on the product category.

**Example:**
Dataset 1 Row: `{'PID': 103, 'P_Name': 'Smartphone', 'Cat_Code': 'ELC', 'Loc': 'TX'}`
Dataset 3 Row: `{'SupplierID': 203, 'Prod_Code': 'ELC', 'Sup_Name': 'Mobile World', 'S_Location': 'Texas'}`

**3. Join Dataset 2 and Dataset 3 (less probable but possible):**

- **Join Keys:** `S_Loc` from Dataset 2 and `S_Location` from Dataset 3 providing they can be normalized to match (like standardizing state names or abbreviations).
- **Reason:**
  - Both columns represent locations (`S_Loc` and `S_Location`), although one is abbreviated and the other is full state names.
  - This join can suggest a linkage between sales locations and supplier locations, indicating where products may be supplied and sold.

**Example:**
Dataset 2 Row: `{'SaleID': 1002, 'Prod_ID': 103, 'S_Price': 700, 'S_Loc': 'TX'}`
Dataset 3 Row: `{'SupplierID': 203, 'Prod_Code': 'ELC', 'Sup_Name': 'Mobile World', 'S_Location': 'Texas'}`

By considering these possible join keys, you can understand the relationships between datasets and extract meaningful insights through various combinations of joins. The most probable and straightforward joins would be based on unique identifiers and category codes, while joins based on locations require additional preprocessing such as standardizing the location formats.

In [ ]:
merged_df = pd.merge(df1, df2, left_on='PID', right_on='Prod_ID', how='inner')

In [ ]:
merged_df.head()

   PID      P_Name Cat_Code Loc  SaleID  Prod_ID  S_Price S_Loc
0  101      Laptop      ELC  NY    1001      101     1000    NY
1  102  Desk Chair      FUR  CA    1003      102      150    CA
2  103  Smartphone      ELC  TX    1002      103      700    TX
3  104   Bookshelf      FUR  IL    1004      104      200    IL
4  105      Tablet      ELC  FL    1006      105      800    FL

In [ ]:
cols = merged_df.columns.tolist()

In [ ]:
cols

['PID', 'P_Name', 'Cat_Code', 'Loc', 'SaleID', 'Prod_ID', 'S_Price', 'S_Loc']

In [ ]:
out = get_multiple_columns_suggestions(cols, "4o")

In [ ]:
final_out = out.split('\n\n')
for suggestion in final_out:
  print(suggestion)
  print('\n\n')

Based on the provided columns, here are some suggestions for columns that can be used together to perform semantic sorting of the dataset along with explanations:



1. **[Cat_Code, P_Name]**
   - **Explanation:** 'Cat_Code' likely represents a category code which can be used to group products into different categories. 'P_Name' is the name of the product. Sorting first by 'Cat_Code' groups all products within the same category together, and then sorting by 'P_Name' alphabetically orders the products within each category.



2. **[Loc, S_Loc]**
   - **Explanation:** 'Loc' indicates the location, which could be a warehouse, region, or store where the product is available. 'S_Loc' is likely the sales location. Sorting first by 'Loc' to group products by their storage or primary location, and then by 'S_Loc' to organize them by their sales locations within the storage location, provides a meaningful hierarchical arrangement.



3. **[Loc, Cat_Code]**
   - **Explanation:** Sorting by 'Loc' first to group products by location, and then by 'Cat_Code' to organize products within each location by their category, provides a way to see which categories of products are available in each location.



4. **[Cat_Code, S_Price]**
   - **Explanation:** Sorting by 'Cat_Code' first to group products by category, and then by 'S_Price' to sort products within each category by their selling price, helps in analyzing the price distribution within each category.



5. **[Loc, S_Price]**
   - **Explanation:** Sorting by 'Loc' first to group products by location, and then by 'S_Price' to sort products within each location by their selling price, provides an overview of the price range of products available in each location.



Each pair of columns suggested above leverages hierarchical (e.g., location and category) or categorical (e.g., category code) relationships to enable meaningful semantic sorting of the dataset. Primary keys ('PID', 'SaleID', 'Prod_ID'), personal names ('P_Name'), and other columns not suitable for semantic sorting have been excluded from these suggestions.

In [ ]:
merged_df['Cat_Code'].unique().tolist()

['ELC', 'FUR']

In [ ]:
cat_prodName = semantic_sort_multiple_column("Cat_Code", merged_df['Cat_Code'].unique().tolist() , "P_Name ", merged_df['P_Name'].unique().tolist())

In [ ]:
final_cat_prod = cat_prodName.split("\n\n")
for suggestion in final_cat_prod:
  print(suggestion)
  print("\n")

Here is a semantic sorting of the combined values of the Cat_Code and P_Name columns:


1. ELC - Laptop
2. ELC - Smartphone
3. ELC - Tablet
4. FUR - Desk Chair
5. FUR - Bookshelf
6. FUR - Table
7. FUR - Office Lamp


The sorting criteria for the combined column are based on the relationship between the categories (Cat_Code) and the products (P_Name). The rationale behind the sorting is as follows:


- Electronics (ELC) are typically considered more essential and modern than furniture (FUR) in a typical office or household setting. Therefore, electronic devices like laptops, smartphones, and tablets are placed before furniture items like desk chairs, bookshelves, tables, and office lamps.


- Within each category, the products are arranged based on their common usage and significance in an office or household environment. For example, a laptop and a smartphone are often considered more indispensable and versatile than a tablet. Similarly, a desk chair is more essential than a bookshelf, table, and office lamp in a typical workspace setup.


This sorting takes into account the common understanding of the importance, functionality, and typical usage scenarios of the products within the given categories.

## Week 5

### joining tables and generating sort suggestions

In [ ]:
import pandas as pd

employee_info = pd.DataFrame({
    "EmployeeID": [1, 2, 3, 4, 5],
    "Name": ["John Smith", "Jane Doe", "Emily Davis", "Michael Brown", "Sarah Wilson"],
    "Department": ["IT", "Marketing", "IT", "HR", "Marketing"],
    "HireDate": ["2015-03-15", "2018-07-24", "2012-09-30", "2019-01-11", "2016-05-20"],
    "Salary": [85000, 62000, 92000, 56000, 73000]
})

employee_performance = pd.DataFrame({
    "EmpID": [1, 2, 3, 4, 5],
    "PerformanceScore": [4.5, 3.9, 4.7, 3.6, 4.1],
    "LastEvaluation": ["2023-01-15", "2023-01-20", "2023-01-10", "2023-01-25", "2023-01-30"],
    "Bonus": [5000, 3000, 5500, 2500, 4000]
})

project_assignments = pd.DataFrame({
    "Employee_ID": [1, 2, 3, 4, 5],
    "ProjectID": [101, 102, 103, 104, 105],
    "ProjectName": ["Alpha", "Beta", "Gamma", "Delta", "Epsilon"],
    "StartDate": ["2022-01-01", "2021-03-15", "2023-05-01", "2020-06-01", "2019-11-01"],
    "EndDate": ["2022-12-31", "2022-03-14", "2023-10-31", "2021-05-31", "2020-10-31"]
})

department_budgets = pd.DataFrame({
    "DeptID": ["D001", "D002", "D003", "D001", "D002"],
    "DepartmentName": ["IT", "Marketing", "HR", "IT", "Marketing"],
    "Year": [2022, 2022, 2022, 2023, 2023],
    "Budget": [500000, 300000, 200000, 550000, 320000]
})

employee_info_sample = employee_info.sample(3)
employee_performance_sample = employee_performance.sample(3)
project_assignments_sample = project_assignments.sample(3)
department_budgets_sample = department_budgets.sample(3)

print("Sampled Employee Information")
print(employee_info_sample)
print("\nSampled Employee Performance")
print(employee_performance_sample)
print("\nSampled Project Assignments")
print(project_assignments_sample)
print("\nSampled Department Budgets")
print(department_budgets_sample)

Sampled Employee Information
   EmployeeID           Name Department    HireDate  Salary
3           4  Michael Brown         HR  2019-01-11   56000
4           5   Sarah Wilson  Marketing  2016-05-20   73000
2           3    Emily Davis         IT  2012-09-30   92000

Sampled Employee Performance
   EmpID  PerformanceScore LastEvaluation  Bonus
4      5               4.1     2023-01-30   4000
2      3               4.7     2023-01-10   5500
3      4               3.6     2023-01-25   2500

Sampled Project Assignments
   Employee_ID  ProjectID ProjectName   StartDate     EndDate
3            4        104       Delta  2020-06-01  2021-05-31
1            2        102        Beta  2021-03-15  2022-03-14
4            5        105     Epsilon  2019-11-01  2020-10-31

Sampled Department Budgets
  DeptID DepartmentName  Year  Budget
2   D003             HR  2022  200000
4   D002      Marketing  2023  320000
1   D002      Marketing  2022  300000

In [ ]:
samples = f'Dataset 1: {employee_info_sample}\nDataset 2: {employee_performance_sample}\nDataset 3: {project_assignments_sample}\nDataset 4: {department_budgets_sample}'

In [ ]:
joinable_datasets = identify_joinable_datasets_with_samples(samples, "4o")
print("Joinable Datasets:")
print(joinable_datasets)

Joinable Datasets:
From the provided samples, we can identify multiple potential joins based on the overlapping key fields:

### Most Probable Join:
1. **Dataset 1 and Dataset 2 on EmployeeID/EmpID**:
   - **Join Key**: `EmployeeID` (Dataset 1) and `EmpID` (Dataset 2).
   - **Reason**: Both datasets have a list of employees which can be matched based on their IDs. This join will combine employee information such as name, department, hire date, and salary from Dataset 1 with performance scores, last evaluation dates, and bonuses from Dataset 2.

   **Example Join Command for SQL**:
   ```sql
   SELECT
       d1.EmployeeID, d1.Name, d1.Department, d1.HireDate, d1.Salary,
       d2.PerformanceScore, d2.LastEvaluation, d2.Bonus
   FROM
       Dataset1 d1
   JOIN
       Dataset2 d2 ON d1.EmployeeID = d2.EmpID;
   ```

### Other Possible Joins:

2. **Dataset 1 and Dataset 3 on EmployeeID/Employee_ID**:
   - **Join Key**: `EmployeeID` (Dataset 1) and `Employee_ID` (Dataset 3).
   - **Reason**: Both datasets reference the same list of employees. This join combines employee information with project details, linking each employee to the projects they have worked on.

   **Example Join Command for SQL**:
   ```sql
   SELECT
       d1.EmployeeID, d1.Name, d1.Department, d1.HireDate, d1.Salary,
       d3.ProjectID, d3.ProjectName, d3.StartDate, d3.EndDate
   FROM
       Dataset1 d1
   JOIN
       Dataset3 d3 ON d1.EmployeeID = d3.Employee_ID;
   ```

3. **Dataset 1 and Dataset 4 on Department/DepartmentName**:
   - **Join Key**: `Department` (Dataset 1) and `DepartmentName` (Dataset 4).
   - **Reason**: Both datasets contain department information. This join combines employee details with department budget information to provide a complete view of employee allocation and department budgets.

   **Example Join Command for SQL**:
   ```sql
   SELECT
       d1.EmployeeID, d1.Name, d1.Department, d1.HireDate, d1.Salary,
       d4.Year, d4.Budget
   FROM
       Dataset1 d1
   JOIN
       Dataset4 d4 ON d1.Department = d4.DepartmentName;
   ```

4. **Dataset 4 on DepartmentName/DepartmentName**:
   - **Join Key**: `DepartmentName` for self-join.
   - **Reason**: This join can be useful to compare budget changes over different years for the same department.

   **Example Join Command for SQL**:
   ```sql
   SELECT
       d4_1.DeptID, d4_1.DepartmentName, d4_1.Year AS Year1, d4_1.Budget AS Budget1,
       d4_2.Year AS Year2, d4_2.Budget AS Budget2
   FROM
       Dataset4 d4_1
   JOIN
       Dataset4 d4_2 ON d4_1.DepartmentName = d4_2.DepartmentName
   WHERE
       d4_1.Year <> d4_2.Year;
   ```

### Summary:
- The most probable join is between Dataset 1 and Dataset 2 on `EmployeeID`.
- Additional useful joins include Dataset 1 with Dataset 3 on `EmployeeID` and Dataset 1 with Dataset 4 on `DepartmentName`.
- Self-joins on Dataset 4 are useful for budget comparisons across years within the same department.

#### merging

In [ ]:
merged_df = pd.merge(employee_info, employee_performance, left_on='EmployeeID', right_on='EmpID')

In [ ]:
merged_df

,EmployeeID,Name,Department,HireDate,Salary,EmpID,PerformanceScore,LastEvaluation,Bonus
0,1,John Smith,IT,2015-03-15,85000,1,4.5,2023-01-15,5000
1,2,Jane Doe,Marketing,2018-07-24,62000,2,3.9,2023-01-20,3000
2,3,Emily Davis,IT,2012-09-30,92000,3,4.7,2023-01-10,5500
3,4,Michael Brown,HR,2019-01-11,56000,4,3.6,2023-01-25,2500
4,5,Sarah Wilson,Marketing,2016-05-20,73000,5,4.1,2023-01-30,4000

In [ ]:
col_suggestions = get_multiple_columns_suggestions(merged_df.columns, mod="4o").split('\n\n')

In [ ]:
for sugg in col_suggestions:
  print(sugg)
  print()

Sure, here are five suggestions for pairs of columns that can be used together for semantic sorting of the dataset, excluding primary keys, unique identifiers, and names:

1. [Department, PerformanceScore]
   - Explanation: Sorting by Department first enables grouping employees by their respective departments, providing a categorical context. Within each department, sorting by PerformanceScore allows for a hierarchical evaluation of employees based on their performance.

2. [Department, Salary]
   - Explanation: Sorting by Department helps in categorizing employees into their respective departments. Within each department, sorting by Salary can provide insight into the salary distribution and possibly identify salary hierarchies within departments.

3. [Department, LastEvaluation]
   - Explanation: First sorting by Department groups employees categorically. Within each department, sorting by LastEvaluation (presumably a date or a score) can help in understanding the timeline or the recency of evaluations, which can be useful for performance reviews or identifying recent achievers.

4. [HireDate, PerformanceScore]
   - Explanation: Sorting by HireDate first allows for a chronological view of when employees were hired. Within the same hire date, sorting by PerformanceScore can help in assessing the performance of employees hired at the same time, potentially highlighting the progress or success of recent hires.

5. [HireDate, Salary]
   - Explanation: Sorting by HireDate provides a timeline of employment. Within each hire date, sorting by Salary can show the salary progression of employees hired at similar times, which can be useful for analyzing pay equity or trends over time.

By focusing on these pairs, we leverage hierarchical, contextual, or categorical relationships within the dataset, ensuring the sorting is meaningful and avoids the use of unique identifiers or personal names.

In [ ]:
dept = semantic_cort_column('Department', merged_df['Department'].unique()).split('\n\n')

In [ ]:
for d in dept:
  print(d)

Sure! Here are five different ways to sort the values ['IT', 'Marketing', 'HR'] based on their semantic meaning for the column 'Department':
1. **Functionality Sorting:**
   - HR, IT, Marketing
   - Sort based on the functionality and purpose within a typical organization. HR (Human Resources) handles employee-related matters, IT (Information Technology) manages technology systems, and Marketing focuses on promoting products or services.
2. **Business Hierarchy Sorting:**
   - IT, Marketing, HR
   - Arrange the departments based on their typical position in a corporate hierarchy. IT often holds a more technical and critical role, followed by Marketing responsible for revenue generation, and HR handling employee welfare.
3. **Strategic Importance Sorting:**
   - Marketing, IT, HR
   - Sort based on the strategic importance of each department. Marketing is crucial for revenue generation and brand visibility, followed by IT for technological infrastructure support, and then HR for employee management.
4. **Resource Allocation Sorting:**
   - IT, HR, Marketing
   - Arrange departments based on resource allocation priorities. IT typically requires significant resources for technology and infrastructure, followed by HR for employee development and well-being, and Marketing for promotional activities.
5. **Interdepartmental Collaboration Sorting:**
   - Marketing, HR, IT
   - Sort based on the need for collaboration between departments. Marketing often collaborates with HR for employer branding and with IT for digital marketing strategies. HR may interact with IT for HR software and systems.
These different sorting criteria provide a unique perspective on arranging the departments in a meaningful way that goes beyond alphabetical order.

In [ ]:
dept_score = semantic_sort_multiple_column2("Department", merged_df['Department'].unique(), "PerformanceScore", merged_df['PerformanceScore'].unique())
dept_score = dept_score.split('\n\n')

In [ ]:
for sugg in dept_score:
  print(sugg)
  print()

# consider giving the new dataframe with only these two columns and generating sort suggestions ---> DONE

To generate all unique combinations of values from the columns Department and PerformanceScore, we first list out the unique values in each column:

- Department: ['IT' 'Marketing' 'HR']
- PerformanceScore: [4.5 3.9 4.7 3.6 4.1]

Now, we combine the values from the two columns to get all unique pairs:

1. IT - 4.5
2. IT - 3.9
3. IT - 4.7
4. IT - 3.6
5. IT - 4.1
6. Marketing - 4.5
7. Marketing - 3.9
8. Marketing - 4.7
9. Marketing - 3.6
10. Marketing - 4.1
11. HR - 4.5
12. HR - 3.9
13. HR - 4.7
14. HR - 3.6
15. HR - 4.1

Next, we will semantically sort these combined values based on their potential real-world connections and logical relationships:

1. High-Performing Department Employees:
   - HR - 4.7
   - IT - 4.7
   - Marketing - 4.7
   - IT - 4.5
   - HR - 4.5
   - Marketing - 4.5
   - Marketing - 4.1
   - IT - 4.1
   - HR - 4.1

2. Average-Performing Department Employees:
   - IT - 3.9
   - HR - 3.9
   - Marketing - 3.9

3. Low-Performing Department Employees:
   - IT - 3.6
   - HR - 3.6

The sorting criteria are based on the assumption that higher performance scores are generally desired in the workplace, so employees with higher scores are placed before those with lower scores. Within each performance score level, the departments are sorted alphabetically. This approach reflects the real-world scenario where high-performing employees are often recognized and rewarded, and where departments are typically arranged in a standardized order.

Please let me know if you need further assistance or more details on this topic.

In [ ]:
dept_score_all_rows = semantic_sort_multiple_columns_all_rows("Department", merged_df['Department'], "PerformanceScore", merged_df['PerformanceScore'])
dept_score_all_rows = dept_score_all_rows.split('\n\n')

In [ ]:
for sugg in dept_score_all_rows:
  print(sugg)
  print()

To sort the provided rows semantically based on the combined values of 'Department' and 'PerformanceScore', we need to consider the context and relationships between departments and performance scores in a typical workplace setting.

The sorting criteria could be based on the following considerations:

1. **PerformanceScore**: Generally, higher performance scores indicate better performance. So, rows with higher performance scores may be prioritized over those with lower scores.

2. **Department**: Different departments may have different performance expectations or standards. For example, IT departments may require higher technical skills and attention to detail compared to marketing departments, where creativity and communication skills might be more valued.

3. **Interdepartmental Comparison**: If we have multiple entries from the same department, we can compare the performance scores within that department to identify the top performers within the same team.

Based on these considerations, we can sort the given rows as follows:

1. ('IT', 4.7) - This row has the highest performance score within the IT department, indicating a top performer in a technical field.

2. ('IT', 4.5) - This row is the second-highest performance score within the IT department, showing a strong performer but slightly lower than the previous entry.

3. ('Marketing', 4.1) - This row represents the highest performance score within the Marketing department, demonstrating a strong performer in a creative and communication-focused role.

4. ('Marketing', 3.9) - This row has a lower performance score within the Marketing department compared to the previous entry, indicating a slightly lower performer in a similar context.

5. ('HR', 3.6) - This row has the lowest performance score among all entries, potentially reflecting the differences in performance expectations or standards for HR roles compared to technical or marketing roles.

Therefore, the sorted rows based on the combined values of 'Department' and 'PerformanceScore' in a real-world context would be:
1. ('IT', 4.7)
2. ('IT', 4.5)
3. ('Marketing', 4.1)
4. ('Marketing', 3.9)
5. ('HR', 3.6)

This sorting order considers the performance scores within each department and the general expectation of performance levels across different departments.

## ex 2

In [ ]:
import pandas as pd

customer_info = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4, 5],
    "Name": ["John Smith", "Jane Doe", "Emily Davis", "Michael Brown", "Sarah Wilson"],
    "Age": [35, 28, 42, 30, 45],
    "City": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
    "State": ["NY", "CA", "IL", "TX", "AZ"],
    "AnnualIncome": [120000, 95000, 140000, 85000, 110000]
})

product_purchases = pd.DataFrame({
    "Cust_ID": [1, 2, 3, 4, 5],
    "ProductID": [101, 102, 103, 104, 105],
    "ProductName": ["Laptop", "Smartphone", "Tablet", "Headphones", "Camera"],
    "PurchaseDate": ["2023-01-15", "2023-01-20", "2023-01-10", "2023-01-25", "2023-01-30"],
    "Price": [1200, 800, 500, 200, 100]
})


customer_reviews = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5],
    "PID": [101, 102, 103, 104, 105],
    "ReviewRating": [4.5, 3.9, 4.7, 3.6, 4.1],
    "ReviewDate": ["2023-02-05", "2023-02-10", "2023-02-03", "2023-02-15", "2023-02-20"]
})

print("Customer Information Dataset:")
print(customer_info)
print()
print("Product Purchases Dataset:")
print(product_purchases)
print()
print("Customer Reviews Dataset:")
print(customer_reviews)

Customer Information Dataset:
   CustomerID           Name  Age         City State  AnnualIncome
0           1     John Smith   35     New York    NY        120000
1           2       Jane Doe   28  Los Angeles    CA         95000
2           3    Emily Davis   42      Chicago    IL        140000
3           4  Michael Brown   30      Houston    TX         85000
4           5   Sarah Wilson   45      Phoenix    AZ        110000

Product Purchases Dataset:
   Cust_ID  ProductID ProductName PurchaseDate  Price
0        1        101      Laptop   2023-01-15   1200
1        2        102  Smartphone   2023-01-20    800
2        3        103      Tablet   2023-01-10    500
3        4        104  Headphones   2023-01-25    200
4        5        105      Camera   2023-01-30    100

Customer Reviews Dataset:
   ID  PID  ReviewRating  ReviewDate
0   1  101           4.5  2023-02-05
1   2  102           3.9  2023-02-10
2   3  103           4.7  2023-02-03
3   4  104           3.6  2023-02-15
4   5  105           4.1  2023-02-20

## ex3

In [ ]:
# Unrelated datasets, to check if gpt can identify joinable ones
import pandas as pd

product_sales = pd.DataFrame({
    "ProductID": [101, 102, 103, 104, 105],
    "ProductName": ["Laptop", "Smartphone", "Tablet", "Smartwatch", "Headphones"],
    "Category": ["Electronics", "Electronics", "Electronics", "Electronics", "Electronics"],
    "Sales": [1500, 3000, 2000, 1800, 2500],
    "Region": ["North America", "Europe", "Asia", "North America", "Europe"]
})

customer_feedback = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4, 5],
    "ProductName": ["Laptop", "Smartphone", "Tablet", "Smartwatch", "Headphones"],
    "Rating": [4.5, 4.7, 4.2, 4.0, 4.3],
    "Feedback": ["Great performance", "Excellent camera", "Good value", "Useful features", "Clear sound"]
})

employee_info = pd.DataFrame({
    "EmployeeID": [201, 202, 203, 204, 205],
    "Name": ["Alice Johnson", "Bob Smith", "Charlie Brown", "Diana Ross", "Eve White"],
    "Department": ["Sales", "Marketing", "IT", "HR", "Finance"],
    "HireDate": ["2016-08-15", "2018-04-22", "2017-05-13", "2019-02-11", "2020-01-20"],
    "Salary": [75000, 68000, 72000, 60000, 80000]
})

regional_climate = pd.DataFrame({
    "Region": ["North America", "Europe", "Asia", "South America", "Africa"],
    "AverageTemperature": [55.5, 49.7, 60.2, 77.8, 81.6],
    "Humidity": [65, 70, 75, 80, 85]
})

product_sales_sample = product_sales.sample(3)
customer_feedback_sample = customer_feedback.sample(3)
employee_info_sample = employee_info.sample(3)
regional_climate_sample = regional_climate.sample(3)

In [ ]:
samples = f'Dataset 1: {product_sales_sample}\nDataset 2: {customer_feedback_sample}\nDataset 3: {employee_info_sample}\nDataset 4: {regional_climate_sample}'

In [ ]:
joinable_datasets = identify_joinable_datasets_with_samples(samples, "4o")
print("Joinable Datasets:")
print(joinable_datasets)

Joinable Datasets:
To determine which datasets can be joined based on the given samples, we need to identify common columns (join keys) among the datasets.

### Most Probable Join Suggestions:

1. **Join between Dataset 1 and Dataset 2:**

    **Join Keys:** ProductName

    **Explanation:** Both datasets have the `ProductName` column, which represents the name of the product. This key allows us to combine records based on the product names.

    **Possible SQL Join:**
    ```sql
    SELECT *
    FROM Dataset1 d1
    JOIN Dataset2 d2
    ON d1.ProductName = d2.ProductName;
    ```

2. **Join between Dataset 1 and Dataset 4:**

    **Join Keys:** Region

    **Explanation:** Both datasets have the `Region` column. This key allows us to combine records based on specific regions.

    **Possible SQL Join:**
    ```sql
    SELECT *
    FROM Dataset1 d1
    JOIN Dataset4 d4
    ON d1.Region = d4.Region;
    ```

### Additional Potential Joins:

3. **Join between Dataset 3 and Dataset 1 via additional metadata (Assuming more data):**

    **Join Keys:** This is speculative based on available data. If there was additional metadata linking employees to regions, departments, or if an intermediary table/metadata connecting `Sales` to `Regions` or `Employees` existed.

### Summary:

- **Primary Joins:**
  - Dataset 1 and Dataset 2: Joined using `ProductName`
  - Dataset 1 and Dataset 4: Joined using `Region`

These joins allow combining datasets based on common product names and regions, respectively. This merging can provide valuable insights, such as how product feedback corresponds to sales performance by region or the effect of climate conditions on regional sales.

In [ ]:
merged_df3 = pd.merge(product_sales, customer_feedback, left_on='ProductName', right_on='ProductName')

In [ ]:
merged_df3

,ProductID,ProductName,Category,Sales,Region,CustomerID,Rating,Feedback
0,101,Laptop,Electronics,1500,North America,1,4.5,Great performance
1,102,Smartphone,Electronics,3000,Europe,2,4.7,Excellent camera
2,103,Tablet,Electronics,2000,Asia,3,4.2,Good value
3,104,Smartwatch,Electronics,1800,North America,4,4.0,Useful features
4,105,Headphones,Electronics,2500,Europe,5,4.3,Clear sound

In [ ]:
col_suggestions = get_multiple_columns_suggestions(merged_df3.columns, mod="4o")

In [ ]:
col_suggestions

"1. **[Category, ProductName]**\n   - **Explanation:** Sorting first by 'Category' groups products into meaningful clusters based on their type. Within each category, sorting by 'ProductName' alphabetically arranges the products, making it easier to find specific items within a category.\n\n2. **[Region, Sales]**\n   - **Explanation:** Sorting by 'Region' first organizes the data geographically, grouping sales data by location. Within each region, sorting by 'Sales' allows for an analysis of performance, showing which products are selling best within each region.\n\n3. **[Category, Sales]**\n   - **Explanation:** Sorting by 'Category' groups products by type, and within each category, sorting by 'Sales' highlights the most and least popular products, providing insight into sales performance across different product types.\n\n4. **[Category, Rating]**\n   - **Explanation:** Sorting by 'Category' groups products by type. Within each category, sorting by 'Rating' allows for a comparison of customer satisfaction, showing which products are most highly rated within each category.\n\n5. **[Region, Rating]**\n   - **Explanation:** Sorting by 'Region' organizes the data geographically. Within each region, sorting by 'Rating' highlights customer satisfaction levels, showing which products are most and least favored in different regions.\n\n### Excluded Columns:\n- **ProductID**: This is a unique identifier and does not provide semantic value for sorting in the context of the product's attributes.\n- **CustomerID**: This is a unique identifier for customers and is not relevant for semantic sorting in the context of product attributes or sales data.\n- **Feedback**: This text column is not suitable for semantic sorting as it contains qualitative data that cannot be easily ordered or categorized."

In [ ]:
region = semantic_cort_column('Region', merged_df3['Region'].unique()).split('\n\n')

In [ ]:
for sugg in region:
  print(sugg)
  print()

1. **Geographical Continuity:**
   - Asia, Europe, North America
   - Sorting based on the order of geographical proximity, with Asia being the closest to Europe and North America being the farthest.

2. **Economic Development:**
   - Europe, North America, Asia
   - Sorting based on the general economic development of the regions, with Europe and North America typically considered more economically developed than Asia.

3. **Historical Perspective:**
   - Europe, Asia, North America
   - Sorting based on historical timelines, with Europe having a longer history of civilization compared to Asia and North America.

4. **Cultural Diversity:**
   - Asia, Europe, North America
   - Sorting based on cultural diversity, with Asia having a wide range of cultures, languages, and traditions compared to Europe and North America.

5. **Population Density:**
   - Asia, Europe, North America
   - Sorting based on population density, with Asia being the most populous continent followed by Europe and then North America.

## ex4

In [ ]:
import pandas as pd
import numpy as np

customer_data = {
    "CustID_1": np.arange(1, 6),
    "Cust_Name": ["John Doe", "Jane Smith", "Emily Johnson", "Michael Brown", "Chris Davis"],
    "Age_Cust": np.random.randint(20, 50, size=5),
    "Email_ID": ["john.doe@example.com", "jane.smith@example.com", "emily.johnson@example.com", "michael.brown@example.com", "chris.davis@example.com"],
    "Loyalty_Level": ["Gold", "Silver", "Gold", "Bronze", "Silver"],
    "Total_Spend": np.random.uniform(1000, 10000, size=5)
}
customer_df = pd.DataFrame(customer_data)
print("Customer Data:\n", customer_df)

product_data = {
    "ProdID_2": np.arange(101, 111),
    "Prod_Name": ["Laptop", "Smartphone", "Tablet", "Monitor", "Keyboard", "Mouse", "Printer", "Scanner", "Camera", "Headphones"],
    "Category_Prod": ["Electronics", "Electronics", "Electronics", "Electronics", "Accessories", "Accessories", "Office Supplies", "Office Supplies", "Photography", "Audio"],
    "Price_Amount": np.random.uniform(100, 1000, size=10),
    "Stock_Level": np.random.randint(10, 200, size=10)
}
product_df = pd.DataFrame(product_data)
print("\nProduct Data:\n", product_df)

order_data = {
    "OrderID_3": np.arange(1001, 1006),
    "CustID_3": np.random.choice(customer_data["CustID_1"], size=5),
    "ProdID_3": np.random.choice(product_data["ProdID_2"], size=5),
    "Quantity_Ordered": np.random.randint(1, 5, size=5),
    "OrderDate_3": pd.date_range(start='2023-01-01', periods=5, freq='D'),
    "Order_Value": np.random.uniform(100, 1000, size=5)
}
order_df = pd.DataFrame(order_data)
print("\nOrder Data:\n", order_df)

employee_data = {
    "EmpID_4": np.arange(1, 11),
    "Emp_Name": ["Alice Green", "Bob White", "Carol Black", "David Blue", "Eve Grey", "Frank Brown", "Grace White", "Hannah Black", "Ivy Blue", "Jack Grey"],
    "Dept_Emp": ["HR", "IT", "Finance", "Marketing", "Sales", "HR", "IT", "Finance", "Marketing", "Sales"],
    "Salary_Amt": np.random.uniform(30000, 70000, size=10),
    "Years_Experience": np.random.randint(1, 20, size=10)
}
employee_df = pd.DataFrame(employee_data)
print("\nEmployee Data:\n", employee_df)

sales_data = {
    "TransID_5": np.arange(2001, 2006),
    "ProdID_5": np.random.choice(product_data["ProdID_2"], size=5),
    "SaleDate_5": pd.date_range(start='2023-02-01', periods=5, freq='W'),
    "SaleAmt_5": np.random.uniform(200, 2000, size=5),
    "Region": ["North", "South", "East", "West", "Central"]
}
sales_df = pd.DataFrame(sales_data)
print("\nSales Data:\n", sales_df)

Customer Data:
    CustID_1      Cust_Name  Age_Cust                   Email_ID Loyalty_Level  \
0         1       John Doe        35       john.doe@example.com          Gold
1         2     Jane Smith        43     jane.smith@example.com        Silver
2         3  Emily Johnson        22  emily.johnson@example.com          Gold
3         4  Michael Brown        38  michael.brown@example.com        Bronze
4         5    Chris Davis        23    chris.davis@example.com        Silver

   Total_Spend
0  3673.522170
1  8673.353429
2  7523.606415
3  3838.356624
4  9765.221314

Product Data:
    ProdID_2   Prod_Name    Category_Prod  Price_Amount  Stock_Level
0       101      Laptop      Electronics    408.130785          112
1       102  Smartphone      Electronics    977.915171          107
2       103      Tablet      Electronics    840.532400           84
3       104     Monitor      Electronics    803.867547           92
4       105    Keyboard      Accessories    408.801327           83
5       106       Mouse      Accessories    586.588565          125
6       107     Printer  Office Supplies    182.492736          110
7       108     Scanner  Office Supplies    704.446348           22
8       109      Camera      Photography    635.946241          115
9       110  Headphones            Audio    704.524199          100

Order Data:
    OrderID_3  CustID_3  ProdID_3  Quantity_Ordered OrderDate_3  Order_Value
0       1001         4       108                 2  2023-01-01   314.443467
1       1002         2       108                 4  2023-01-02   289.185127
2       1003         3       107                 4  2023-01-03   457.922418
3       1004         4       108                 4  2023-01-04   463.472919
4       1005         1       102                 3  2023-01-05   828.988543

Employee Data:
    EmpID_4      Emp_Name   Dept_Emp    Salary_Amt  Years_Experience
0        1   Alice Green         HR  62141.534765                18
1        2     Bob White         IT  56791.163266                 6
2        3   Carol Black    Finance  36102.174115                 3
3        4    David Blue  Marketing  55458.943380                17
4        5      Eve Grey      Sales  35122.659865                18
5        6   Frank Brown         HR  36253.736802                15
6        7   Grace White         IT  40513.237790                 7
7        8  Hannah Black    Finance  42073.834677                 5
8        9      Ivy Blue  Marketing  64489.577682                13
9       10     Jack Grey      Sales  35419.502979                 8

Sales Data:
    TransID_5  ProdID_5 SaleDate_5    SaleAmt_5   Region
0       2001       106 2023-02-05  1968.425771    North
1       2002       101 2023-02-12  1792.121683    South
2       2003       105 2023-02-19   881.408068     East
3       2004       107 2023-02-26   911.543895     West
4       2005       103 2023-03-05   418.590780  Central

In [ ]:
customer_df_sample = customer_df.sample(2)
product_df_sample = product_df.sample(2)
order_df_sample = order_df.sample(2)
employee_df_sample = employee_df.sample(2)
sales_df_sample = sales_df.sample(2)

In [ ]:
samples4 = f"Dataset1: {customer_df_sample}\nDataset2: {product_df_sample}\nDataset3: {order_df_sample}\nDataset4: {employee_df_sample}\nDataset5: {sales_df_sample}\n"

In [ ]:
joinable_suggestions = identify_joinable_datasets_with_samples(samples4, mod='4o').split('\n\n')

In [ ]:
for sugg in joinable_suggestions:
  print(sugg)
  print()

To determine which datasets can be joined based on the content of the rows, we need to identify common attributes that can serve as join keys.

### Most Probable Joins:

1. **Dataset1 and Dataset3**:
    - **Join Key(s)**: `CustID` from Dataset1 (CustID_1) and Dataset3 (CustID_3)
    - **Reason**: Both datasets contain a `CustID` attribute which corresponds to customer identifiers. This can be used to link customer information with their orders.
    - **Join Example**:
      - Dataset1: CustID_1 = 1 (John Doe)
      - Dataset3: CustID_3 = 1 (OrderID_3 = 1003, OrderDate_3 = 2023-01-03)
    - **Result**: Linking customers to their orders.

2. **Dataset2 and Dataset3**:
    - **Join Key(s)**: `ProdID` from Dataset2 (ProdID_2) and Dataset3 (ProdID_3)
    - **Reason**: Both datasets have a `ProdID` attribute that identifies products. This can be used to link product details with the orders.
    - **Join Example**:
      - Dataset2: ProdID_2 = 104 (Accessory)
      - Dataset3: ProdID_3 = 104 (OrderID_3 = 1003)
    - **Result**: Associating product details with each order.

3. **Dataset2 and Dataset5**:
    - **Join Key(s)**: `ProdID` from Dataset2 (ProdID_2) and Dataset5 (ProdID_5)
    - **Reason**: Both datasets contain a `ProdID` which represents product identifiers.
    - **Join Example**:
      - Dataset2: ProdID_2 = 104 (Accessory)
      - Dataset5: ProdID_5 = 104 (SaleDate_5 = 2023-02-05)
    - **Result**: Matching product details with sales transactions.

4. **Dataset3 and Dataset5**:
    - **Join Key(s)**: `ProdID` from Dataset3 (ProdID_3) and Dataset5 (ProdID_5)
    - **Reason**: Both datasets contain a `ProdID` which can link order details with sales transactions.
    - **Join Example**:
      - Dataset3: ProdID_3 = 104 (OrderID_3 = 1003)
      - Dataset5: ProdID_5 = 104 (SaleDate_5 = 2023-02-05)
    - **Result**: Connecting orders to subsequent sales data.

### Less Probable Joins (No clear matching attributes observed):

5. **Dataset1 and Dataset5, Dataset1 and Dataset2, Dataset2 and Dataset4, Dataset3 and Dataset4, Dataset4 and Dataset5**:
    - **Reason**: These dataset pairs do not have any apparent common join keys based on the provided attributes. Hence, no direct joins can be suggested between these pairs without additional context or transformation.

### Conclusion:
The datasets can most reliably be joined on these combinations:
1. **Dataset1 to Dataset3** via `CustID`,
2. **Dataset2 to Dataset3** via `ProdID`,
3. **Dataset2 to Dataset5** via `ProdID`,
4. **Dataset3 to Dataset5** via `ProdID`.

These joins enable linking customer data to orders, product details to orders, product details to sales transactions, and orders to sales transactions respectively.

In [ ]:
# Idea 6: Combining Three Datasets (Dataset1, Dataset3, Dataset2)
merged_df1 = pd.merge(customer_df, order_df, left_on='CustID_1', right_on='CustID_3')

In [ ]:
merged_df1

,CustID_1,Cust_Name,Age_Cust,Email_ID,Loyalty_Level,Total_Spend,OrderID_3,CustID_3,ProdID_3,Quantity_Ordered,OrderDate_3,Order_Value
0,1,John Doe,36,john.doe@example.com,Gold,1932.701632,1003,1,104,2,2023-01-03,126.941063
1,2,Jane Smith,35,jane.smith@example.com,Silver,5428.687416,1002,2,108,4,2023-01-02,613.368832
2,3,Emily Johnson,25,emily.johnson@example.com,Gold,6965.508843,1004,3,109,1,2023-01-04,866.707770
3,3,Emily Johnson,25,emily.johnson@example.com,Gold,6965.508843,1005,3,108,1,2023-01-05,594.398917
4,4,Michael Brown,21,michael.brown@example.com,Bronze,7717.321484,1001,4,103,1,2023-01-01,611.402381

In [ ]:
merged_df2 = pd.merge(merged_df1, product_df, left_on='ProdID_3', right_on='ProdID_2')

In [ ]:
merged_df2

,CustID_1,Cust_Name,Age_Cust,Email_ID,Loyalty_Level,Total_Spend,OrderID_3,CustID_3,ProdID_3,Quantity_Ordered,OrderDate_3,Order_Value,ProdID_2,Prod_Name,Category_Prod,Price_Amount,Stock_Level
0,1,John Doe,35,john.doe@example.com,Gold,3673.522170,1005,1,102,3,2023-01-05,828.988543,102,Smartphone,Electronics,977.915171,107
1,2,Jane Smith,43,jane.smith@example.com,Silver,8673.353429,1002,2,108,4,2023-01-02,289.185127,108,Scanner,Office Supplies,704.446348,22
2,4,Michael Brown,38,michael.brown@example.com,Bronze,3838.356624,1001,4,108,2,2023-01-01,314.443467,108,Scanner,Office Supplies,704.446348,22
3,4,Michael Brown,38,michael.brown@example.com,Bronze,3838.356624,1004,4,108,4,2023-01-04,463.472919,108,Scanner,Office Supplies,704.446348,22
4,3,Emily Johnson,22,emily.johnson@example.com,Gold,7523.606415,1003,3,107,4,2023-01-03,457.922418,107,Printer,Office Supplies,182.492736,110

In [ ]:
col_suggestions = get_multiple_columns_suggestions(merged_df2.columns, mod="4o").split('\n\n')

In [ ]:
for sugg in col_suggestions:
  print(sugg)
  print()

1. [Loyalty_Level, Total_Spend]
   Explanation: "Loyalty_Level" is typically a categorical variable indicating a customer's membership tier or loyalty status, which can be semantically sorted from lowest to highest level (e.g., Bronze, Silver, Gold, Platinum). "Total_Spend" complements this by providing a numerical value that can be sorted within each loyalty level, giving a clear picture of customer spending within each tier.

2. [Category_Prod, Price_Amount]
   Explanation: "Category_Prod" is a categorical variable that groups products into different categories (e.g., Electronics, Clothing, Groceries). Sorting by this column first helps organize the data by product type. "Price_Amount" can then be used to sort products within each category by their price, allowing for a semantic overview of products from cheapest to most expensive within each category.

3. [Age_Cust, Loyalty_Level]
   Explanation: "Age_Cust" is a numerical variable representing the customer's age, which can be sorted to understand the age distribution of customers. "Loyalty_Level" can be used to further sort within each age group, providing insights into the loyalty status of customers at different ages.

4. [Category_Prod, Stock_Level]
   Explanation: "Category_Prod" sorts products into defined categories, making it easier to analyze inventory by type. "Stock_Level" can then be used to sort products within each category by their current stock levels, highlighting which products are well-stocked versus those that are low in inventory.

5. [OrderDate_3, Order_Value]
   Explanation: "OrderDate_3" allows for chronological sorting of orders, which can be useful for understanding sales trends over time. "Order_Value" can then be used to sort orders within each date, providing a view of the revenue generated daily.

These pairs leverage hierarchical, contextual, or categorical relationships while excluding primary keys, unique identifiers, and personal information, making them suitable for semantic sorting.

In [ ]:
cat_name = semantic_sort_multiple_column("Category_Prod", merged_df2['Category_Prod'].unique(), "Prod_Name", merged_df2['Prod_Name'].unique(), "4o")
cat_name = cat_name.split('\n\n')

In [ ]:
for sugge in cat_name:
  print(sugge)
  print()

To semantically sort the combined values from the columns `Category_Prod` and `Prod_Name`, we need to consider the context and relationship between the categories and products. Here, we will use the utility, dependency, and common usage patterns to determine the order.

### Criteria for Sorting:
1. **Utility and Common Usage**: Products that are more frequently used in everyday tasks or have a higher utility should come first.
2. **Dependency**: Products that enable the use of other products should come first. For instance, a "Printer" might be more foundational than "Printer Ink".
3. **Category Importance**: Some categories might be more crucial or foundational than others in a typical context (e.g., "Office Supplies" might be seen as essential tools for productivity).

### Combined Values:
- Electronics: Smartphone
- Office Supplies: Scanner
- Office Supplies: Printer

### Semantic Sorting:
1. **Electronics: Smartphone** - Smartphones are highly versatile and commonly used devices in both personal and professional settings. They are crucial for communication, internet access, and numerous applications.

2. **Office Supplies: Printer** - Printers are essential office equipment for producing hard copies of documents, which are fundamental in many business operations. They are widely used and have high utility in an office environment.

3. **Office Supplies: Scanner** - Scanners, while important, are generally used less frequently than printers. Their primary function is to digitize physical documents, which is important but often secondary to printing.

### Sorted Values:
1. **Electronics: Smartphone**
2. **Office Supplies: Printer**
3. **Office Supplies: Scanner**

#### Rationale:
- **Smartphone** leads due to its essential role in both personal and professional realms, offering high functionality and frequent use.
- **Printer** follows because it is a core office device with high utility in creating physical documents.
- **Scanner** comes last as its use is more specialized and less frequent compared to the other items.

This sorting leverages utility, dependency, and common usage patterns rather than alphabetical order, providing a more contextually relevant sequence.

In [ ]:
custom_order = [
    "Electronics - Smartphone",
    "Office Supplies - Printer",
    "Office Supplies - Scanner",
]

order_mapping = {course: index for index, course in enumerate(custom_order)}
print(order_mapping)

# Creating a new column in the dataframe that combines Department and Course_Name
merged_df2['Category_Prod_Combined'] = merged_df2['Category_Prod'] + " - " + merged_df2['Prod_Name']

merged_df2['Order'] = merged_df2['Category_Prod_Combined'].map(order_mapping)

# Sorting the dataframe by Order
merged_df2_sorted = merged_df2.sort_values(by='Order')

# df_sorted.drop(columns=['Department_Course', 'Order'], inplace=True)

{'Electronics - Smartphone': 0, 'Office Supplies - Printer': 1, 'Office Supplies - Scanner': 2}

In [ ]:
merged_df2_sorted

,CustID_1,Cust_Name,Age_Cust,Email_ID,Loyalty_Level,Total_Spend,OrderID_3,CustID_3,ProdID_3,Quantity_Ordered,OrderDate_3,Order_Value,ProdID_2,Prod_Name,Category_Prod,Price_Amount,Stock_Level,Category_Prod_Combined,Order
0,1,John Doe,35,john.doe@example.com,Gold,3673.522170,1005,1,102,3,2023-01-05,828.988543,102,Smartphone,Electronics,977.915171,107,Electronics - Smartphone,0
4,3,Emily Johnson,22,emily.johnson@example.com,Gold,7523.606415,1003,3,107,4,2023-01-03,457.922418,107,Printer,Office Supplies,182.492736,110,Office Supplies - Printer,1
1,2,Jane Smith,43,jane.smith@example.com,Silver,8673.353429,1002,2,108,4,2023-01-02,289.185127,108,Scanner,Office Supplies,704.446348,22,Office Supplies - Scanner,2
2,4,Michael Brown,38,michael.brown@example.com,Bronze,3838.356624,1001,4,108,2,2023-01-01,314.443467,108,Scanner,Office Supplies,704.446348,22,Office Supplies - Scanner,2
3,4,Michael Brown,38,michael.brown@example.com,Bronze,3838.356624,1004,4,108,4,2023-01-04,463.472919,108,Scanner,Office Supplies,704.446348,22,Office Supplies - Scanner,2

In [ ]:
cat_name_all_rows = semantic_sort_multiple_columns_all_rows("Category_Prod", merged_df2['Category_Prod'], "Prod_Name", merged_df2['Prod_Name'])
cat_name_all_rows = cat_name_all_rows.split('\n\n')

In [ ]:
for sugge in cat_name_all_rows:
  print(sugge)
  print()

Based on real-world knowledge and relationships between product categories and specific products, we can sort the given rows semantically as follows:

1. ('Electronics', 'Monitor')
2. ('Electronics', 'Tablet')
3. ('Office Supplies', 'Scanner') - First occurrence
4. ('Office Supplies', 'Scanner') - Second occurrence
5. ('Photography', 'Camera')

**Rationale for the Sorting:**

1. **('Electronics', 'Monitor')**: Monitors are commonly associated with the Electronics category due to their primary function as display devices for electronic devices. They are essential components of electronic setups, making this combination a top priority.

2. **('Electronics', 'Tablet')**: Tablets are also typically categorized under Electronics, as they are portable computing devices. Although tablets are different from monitors in terms of functionality and form factor, they still belong to the same general category.

3. **('Office Supplies', 'Scanner') - First occurrence**: Scanners are often considered essential office supplies, commonly used for digitizing documents and images in office environments. The first occurrence is prioritized over the second occurrence due to the initial association of scanners with office-related tasks.

4. **('Office Supplies', 'Scanner') - Second occurrence**: The second occurrence of ('Office Supplies', 'Scanner') is placed after the first occurrence as it follows a sequential order in terms of a list of items.

5. **('Photography', 'Camera')**: Cameras are primarily linked to the Photography category because they are tools used for capturing images and videos. While cameras can also be used outside of photography-related contexts, the association with photography is stronger and hence placed last in this sorted list.

This sorting takes into account the inherent relationships and typical associations between product categories and specific products, providing a contextual and meaningful sequence based on real-world knowledge.

ex 6

In [ ]:
import pandas as pd
import numpy as np

student_info = {
    "Student_ID": np.arange(1, 7),
    "Student_Name": ["Alice Smith", "Bob Johnson", "Carol White", "David Green", "Eva Black", "Akash Khatri"],
    "Age": np.random.randint(18, 25, size=6),
    "Major": ["Physics", "Mathematics", "Biology", "Chemistry", "Computer Science", "Mathematics"],
    "GPA": np.random.uniform(2.5, 4.0, size=6)
}
student_info_df = pd.DataFrame(student_info)
print("Student Information:\n", student_info_df)

course_info = {
    "Course_ID": np.arange(101, 107),
    "Course_Name": ["Quantum Mechanics", "Linear Algebra", "Genetics", "Organic Chemistry", "Data Structures", "Calculus"],
    "Department": ["Physics", "Mathematics", "Biology", "Chemistry", "Computer Science", "Mathematics"],
    "Credits": [3, 4, 3, 4, 3, 4]
}
course_info_df = pd.DataFrame(course_info)
print("\nCourse Information:\n", course_info_df)

healthcare_records = {
    "Patient_ID": np.arange(201, 206),
    "Patient_Name": ["John Brown", "Linda White", "Mike Green", "Nina Black", "Oliver Blue"],
    "Age": np.random.randint(30, 70, size=5),
    "Disease": ["Diabetes", "Hypertension", "Asthma", "Cancer", "Heart Disease"],
    "Treatment_Cost": np.random.uniform(5000, 20000, size=5)
}
healthcare_records_df = pd.DataFrame(healthcare_records)
print("\nHealthcare Records:\n", healthcare_records_df)

environmental_data = {
    "Location_ID": np.arange(301, 306),
    "City_Name": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
    "Air_Quality_Index": np.random.randint(0, 500, size=5),
    "Water_Quality_Index": np.random.randint(0, 100, size=5),
    "Green_Cover_Percentage": np.random.uniform(10, 50, size=5)
}
environmental_data_df = pd.DataFrame(environmental_data)
print("\nEnvironmental Data:\n", environmental_data_df)

financial_transactions = {
    "Transaction_ID": np.arange(401, 406),
    "Client_ID": np.random.choice(student_info["Student_ID"], size=5),
    "Transaction_Amount": np.random.uniform(100, 1000, size=5),
    "Transaction_Date": pd.date_range(start='2023-01-01', periods=5, freq='M'),
    "Category": ["Tuition", "Books", "Lab Fees", "Hostel", "Miscellaneous"]
}
financial_transactions_df = pd.DataFrame(financial_transactions)
print("\nFinancial Transactions:\n", financial_transactions_df)

research_publications = {
    "Publication_ID": np.arange(501, 506),
    "Author_ID": np.random.choice(student_info["Student_ID"], size=5),
    "Title": ["Quantum Entanglement", "Advanced Calculus", "DNA Sequencing", "Chemical Reactions", "Machine Learning Algorithms"],
    "Journal_Name": ["Phys Rev", "Math Ann", "Bio J", "Chem Soc", "Comp Sci Rev"],
    "Publication_Year": np.random.randint(2015, 2023, size=5)
}
research_publications_df = pd.DataFrame(research_publications)
print("\nResearch Publications:\n", research_publications_df)

weather_data = {
    "Weather_Station_ID": np.arange(601, 606),
    "City_Name_Weather": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
    "Temperature": np.random.uniform(-10, 40, size=5),
    "Humidity": np.random.uniform(20, 90, size=5),
    "Precipitation": np.random.uniform(0, 100, size=5)
}
weather_data_df = pd.DataFrame(weather_data)
print("\nWeather Data:\n", weather_data_df)

university_departments = {
    "Department_ID": np.arange(701, 706),
    "Department_Name": ["Physics", "Mathematics", "Biology", "Chemistry", "Computer Science"],
    "Number_of_Faculty": np.random.randint(10, 50, size=5),
    "Number_of_Students": np.random.randint(100, 500, size=5),
    "Annual_Budget": np.random.uniform(100000, 500000, size=5)
}
university_departments_df = pd.DataFrame(university_departments)
print("\nUniversity Departments:\n", university_departments_df)

Student Information:
    Student_ID  Student_Name  Age             Major       GPA
0           1   Alice Smith   19           Physics  3.796033
1           2   Bob Johnson   21       Mathematics  3.847087
2           3   Carol White   18           Biology  3.693731
3           4   David Green   24         Chemistry  3.613146
4           5     Eva Black   18  Computer Science  3.055498
5           6  Akash Khatri   19       Mathematics  3.925222

Course Information:
    Course_ID        Course_Name        Department  Credits
0        101  Quantum Mechanics           Physics        3
1        102     Linear Algebra       Mathematics        4
2        103           Genetics           Biology        3
3        104  Organic Chemistry         Chemistry        4
4        105    Data Structures  Computer Science        3
5        106           Calculus       Mathematics        4

Healthcare Records:
    Patient_ID Patient_Name  Age        Disease  Treatment_Cost
0         201   John Brown   52       Diabetes    14514.673492
1         202  Linda White   34   Hypertension    10095.465022
2         203   Mike Green   61         Asthma    11308.183986
3         204   Nina Black   39         Cancer     6627.238615
4         205  Oliver Blue   34  Heart Disease    13232.348047

Environmental Data:
    Location_ID    City_Name  Air_Quality_Index  Water_Quality_Index  \
0          301     New York                266                   68
1          302  Los Angeles                212                   65
2          303      Chicago                100                    2
3          304      Houston                167                   15
4          305      Phoenix                484                    2

   Green_Cover_Percentage
0               27.408233
1               12.620807
2               33.080187
3               26.867341
4               20.854825

Financial Transactions:
    Transaction_ID  Client_ID  Transaction_Amount Transaction_Date  \
0             401          1          983.132913       2023-01-31
1             402          1          483.986583       2023-02-28
2             403          5          746.252392       2023-03-31
3             404          1          619.644316       2023-04-30
4             405          3          930.519746       2023-05-31

        Category
0        Tuition
1          Books
2       Lab Fees
3         Hostel
4  Miscellaneous

Research Publications:
    Publication_ID  Author_ID                        Title  Journal_Name  \
0             501          2         Quantum Entanglement      Phys Rev
1             502          3            Advanced Calculus      Math Ann
2             503          6               DNA Sequencing         Bio J
3             504          3           Chemical Reactions      Chem Soc
4             505          6  Machine Learning Algorithms  Comp Sci Rev

   Publication_Year
0              2020
1              2021
2              2015
3              2018
4              2020

Weather Data:
    Weather_Station_ID City_Name_Weather  Temperature   Humidity  Precipitation
0                 601          New York    10.506075  49.465286      69.495369
1                 602       Los Angeles    30.451219  41.359613      54.956477
2                 603           Chicago    -0.407786  84.500459      16.053172
3                 604           Houston    -2.118261  52.282029      31.548361
4                 605           Phoenix    -2.460812  20.395195      59.654559

University Departments:
    Department_ID   Department_Name  Number_of_Faculty  Number_of_Students  \
0            701           Physics                 26                 282
1            702       Mathematics                 49                 195
2            703           Biology                 25                 327
3            704         Chemistry                 39                 358
4            705  Computer Science                 24                 333

   Annual_Budget
0  233689.958090
1  242565.411664
2  243714.857872
3  113173.364012
4  232348.062335

In [ ]:
student_info_sample = student_info_df.sample(3)
course_info_sample = course_info_df.sample(3)
healthcare_records_sample = healthcare_records_df.sample(3)
environmental_data_sample = environmental_data_df.sample(3)
financial_transactions_sample = financial_transactions_df.sample(3)
research_publications_sample = research_publications_df.sample(3)
weather_data_sample = weather_data_df.sample(3)
university_departments_sample = university_departments_df.sample(3)

In [ ]:
samples = f"Dataset1: {student_info_sample}\nDataset2: {course_info_sample}\nDataset3: {healthcare_records_sample}\nDataset4: {environmental_data_sample}\nDataset5: {financial_transactions_sample}\nDataset6: {research_publications_sample}\nDataset7: {weather_data_sample}\nDataset8: {university_departments_sample}\n"

In [ ]:
joinable_datasets = identify_joinable_datasets_with_samples(samples, mod="4o")

In [ ]:
joinable_datasets = joinable_datasets.split('\n\n')

In [ ]:
for sugg in joinable_datasets:
  print(sugg)
  print()

Given the provided dataset samples, let’s analyze which datasets can be potentially joined based on common keys:

1. **Dataset1 and Dataset2:**
   - **Join Key: `Major` in Dataset1 and `Department` in Dataset2.**
   - **Reason:** The `Major` field in Dataset1 represents the academic department which aligns with the `Department` field in Dataset2.

    ```sql
    SELECT * FROM Dataset1 d1
    JOIN Dataset2 d2 ON d1.Major = d2.Department;
    ```

2. **Dataset1 and Dataset8:**
   - **Join Key: `Major` in Dataset1 and `Department_Name` in Dataset8.**
   - **Reason:** `Major` in Dataset1 corresponds to the `Department_Name` in Dataset8 as they both refer to the specific fields of study.

    ```sql
    SELECT * FROM Dataset1 d1
    JOIN Dataset8 d8 ON d1.Major = d8.Department_Name;
    ```

3. **Dataset4 and Dataset7:**
   - **Join Key: `City_Name` in Dataset4 and `City_Name_Weather` in Dataset7.**
   - **Reason:** The city names are represented in both datasets which can be used to join environmental data with weather information.

    ```sql
    SELECT * FROM Dataset4 d4
    JOIN Dataset7 d7 ON d4.City_Name = d7.City_Name_Weather;
    ```

4. **Dataset2 and Dataset8:**
   - **Join Key: `Department` in Dataset2 and `Department_Name` in Dataset8.**
   - **Reason:** There’s a direct correlation between `Department` in Dataset2 and `Department_Name` in Dataset8 as both refer to academic departments.

    ```sql
    SELECT * FROM Dataset2 d2
    JOIN Dataset8 d8 ON d2.Department = d8.Department_Name;
    ```

5. **Potential Joins Based on Assumptions:**

    - Although not directly indicated by the provided samples, the following joins could be considered if more context was provided:

    - **Dataset3 and Dataset7/Dataset4:**
      - **Join Key: `City_Name` if patient residence city was known in Dataset3.**

    - **Common Client/Participant IDs:**
      - If your business logic connects students to authors, clients, or transactions, use `Student_ID`, `Client_ID`, or `Author_ID`.

However, based on the provided dataset samples, the most probable joins without additional contextual assumptions are:

1. **Dataset1 and Dataset2** (Major/Department)
2. **Dataset1 and Dataset8** (Major/Department_Name)
3. **Dataset4 and Dataset7** (City_Name/City_Name_Weather)
4. **Dataset2 and Dataset8** (Department/Department_Name)

These joins are the ones that make the most sense given the column names and logical associations between the datasets.

In [ ]:
merged_df = pd.merge(student_info_df, course_info_df, left_on='Major', right_on='Department')

In [ ]:
merged_df

,Student_ID,Student_Name,Age,Major,GPA,Course_ID,Course_Name,Department,Credits
0,1,Alice Smith,19,Physics,3.796033,101,Quantum Mechanics,Physics,3
1,2,Bob Johnson,21,Mathematics,3.847087,102,Linear Algebra,Mathematics,4
2,2,Bob Johnson,21,Mathematics,3.847087,106,Calculus,Mathematics,4
3,6,Akash Khatri,19,Mathematics,3.925222,102,Linear Algebra,Mathematics,4
4,6,Akash Khatri,19,Mathematics,3.925222,106,Calculus,Mathematics,4
5,3,Carol White,18,Biology,3.693731,103,Genetics,Biology,3
6,4,David Green,24,Chemistry,3.613146,104,Organic Chemistry,Chemistry,4
7,5,Eva Black,18,Computer Science,3.055498,105,Data Structures,Computer Science,3

In [ ]:
col_suggestions = get_multiple_columns_suggestions(merged_df.columns, mod="4o").split('\n\n')

In [ ]:
for sugg in col_suggestions:
  print(sugg)

1. **[Major, GPA]**
   - **Explanation:** Major and GPA can be used together for semantic sorting because students can be grouped by their major, and within each major, they can be sorted by their GPA. This is useful for analyzing academic performance across different fields of study.
2. **[Department, Course_Name]**
   - **Explanation:** Sorting by Department and then by Course_Name allows for organizing courses within their respective academic departments, providing a structured view of the curriculum offered by each department.
3. **[Age, GPA]**
   - **Explanation:** Age and GPA can be used together to explore the academic performance of students across different age groups. This could be insightful for understanding trends or patterns in the academic achievements of younger versus older students.
4. **[Credits, Course_Name]**
   - **Explanation:** Sorting by Credits and then by Course_Name can help in understanding the workload and curriculum structure, showing which courses carry more credits and how they are titled or categorized.
5. **[Major, Credits]**
   - **Explanation:** Using Major and Credits together provides an organizational view of how credit distribution varies across different majors. This can be useful for curriculum planning and understanding the academic rigor associated with each major.
These suggested pairs avoid primary keys, unique identifiers, and personal names, focusing instead on columns that provide meaningful hierarchical, contextual, or categorical relationships suitable for semantic sorting.

In [ ]:
dep_course = semantic_sort_multiple_column("Department", merged_df['Department'].unique(), "Course_Name", merged_df['Course_Name'].unique(), "4o")
dep_course = dep_course.split('\n\n')

In [ ]:
for sugg in dep_course:
  print(sugg)

To provide a semantic sorting of the combined values from the given columns ("Department" and "Course_Name"), we need to consider the inherent relationships between the subjects and their courses. Here, we'll prioritize:
1. Foundational courses that are prerequisites for advanced studies.
2. Courses that are fundamental to the understanding of multiple subjects.
3. The general progression of learning in these fields from basic to advanced.
With these criteria in mind, let's sort the combined values:
1. **Mathematics - Linear Algebra**: Linear Algebra is crucial for many areas of science and engineering, providing a foundation for more complex topics in various disciplines including Physics and Computer Science.
2. **Mathematics - Calculus**: Calculus is another foundational course that is essential for understanding advanced concepts in Physics, Chemistry, Biology, and Computer Science.
3. **Physics - Quantum Mechanics**: Quantum Mechanics is a specialized, advanced topic in Physics, building on foundational knowledge from courses like Linear Algebra and Calculus.
4. **Computer Science - Data Structures**: Data Structures is a fundamental course in Computer Science, critical for understanding how to efficiently store and manipulate data.
5. **Chemistry - Organic Chemistry**: Organic Chemistry is a central course in Chemistry, essential for understanding the structure, properties, and reactions of organic compounds.
6. **Biology - Genetics**: Genetics is a fundamental course in Biology, important for understanding heredity and variation in living organisms.
So, the combined sorted list based on the explained criteria would be:
1. **Mathematics - Linear Algebra**
2. **Mathematics - Calculus**
3. **Physics - Quantum Mechanics**
4. **Computer Science - Data Structures**
5. **Chemistry - Organic Chemistry**
6. **Biology - Genetics**
### Rationale:
- **Mathematics courses (Linear Algebra and Calculus)** are foundational and applicable across multiple disciplines, thus they are placed first.
- **Physics - Quantum Mechanics** relies heavily on understanding advanced mathematics, so it follows after the foundational math courses.
- **Computer Science - Data Structures** is essential for computational thinking and problem-solving, which is foundational within its domain.
- **Chemistry - Organic Chemistry** is a specialized yet central subject within Chemistry.
- **Biology - Genetics** is a foundational course in understanding biological processes and is fundamental within its domain.
This approach ensures that the sorting is based on educational progression and interdisciplinary relevance rather than mere alphabetical order.

In [ ]:
custom_order = [
    "Mathematics - Linear Algebra",
    "Mathematics - Calculus",
    "Physics - Quantum Mechanics",
    "Computer Science - Data Structures",
    "Chemistry - Organic Chemistry",
    "Biology - Genetics"
]

order_mapping = {course: index for index, course in enumerate(custom_order)}
print(order_mapping)

# Creating a new column in the dataframe that combines Department and Course_Name
merged_df['Department_Course'] = merged_df['Department'] + " - " + merged_df['Course_Name']

merged_df['Order'] = merged_df['Department_Course'].map(order_mapping)

# Sorting the dataframe by Order
merged_df_sorted = merged_df.sort_values(by='Order')

# df_sorted.drop(columns=['Department_Course', 'Order'], inplace=True)

{'Mathematics - Linear Algebra': 0, 'Mathematics - Calculus': 1, 'Physics - Quantum Mechanics': 2, 'Computer Science - Data Structures': 3, 'Chemistry - Organic Chemistry': 4, 'Biology - Genetics': 5}

In [ ]:
merged_df_sorted

,Student_ID,Student_Name,Age,Major,GPA,Course_ID,Course_Name,Department,Credits,Department_Course,Order
1,2,Bob Johnson,21,Mathematics,3.847087,102,Linear Algebra,Mathematics,4,Mathematics - Linear Algebra,0
3,6,Akash Khatri,19,Mathematics,3.925222,102,Linear Algebra,Mathematics,4,Mathematics - Linear Algebra,0
2,2,Bob Johnson,21,Mathematics,3.847087,106,Calculus,Mathematics,4,Mathematics - Calculus,1
4,6,Akash Khatri,19,Mathematics,3.925222,106,Calculus,Mathematics,4,Mathematics - Calculus,1
0,1,Alice Smith,19,Physics,3.796033,101,Quantum Mechanics,Physics,3,Physics - Quantum Mechanics,2
7,5,Eva Black,18,Computer Science,3.055498,105,Data Structures,Computer Science,3,Computer Science - Data Structures,3
6,4,David Green,24,Chemistry,3.613146,104,Organic Chemistry,Chemistry,4,Chemistry - Organic Chemistry,4
5,3,Carol White,18,Biology,3.693731,103,Genetics,Biology,3,Biology - Genetics,5

## gpt-4o output

In [ ]:
pos_exp = semantic_sort_multiple_column("Position", "Intern, Junior Developer, Senior Developer, Team Lead, Manager", "Experience_Level", "Entry Level, Mid Level, Senior Level")

In [ ]:
final_pos_exp = pos_exp.split("\n\n")
for suggestion in final_pos_exp:
  print(suggestion)
  print("\n")

To provide a semantic sorting of the combined values from the columns Position and Experience_Level, we need to consider both the typical career progression in the tech industry and the hierarchy implied by the experience levels. Here’s a step-by-step breakdown of the sorting criteria:


1. **Position Hierarchy**: This primarily reflects the job title and its usual place in the career ladder:
   - Intern
   - Junior Developer
   - Senior Developer
   - Team Lead
   - Manager


2. **Experience_Level Hierarchy**: This reflects the experience required for each position:
   - Entry Level
   - Mid Level
   - Senior Level


3. **Combining the Columns**: When we combine Position and Experience_Level, we should consider that certain positions are inherently less experienced even if they have the same experience level label. For example, a "Senior Level Intern" doesn't make sense as "Intern" implies an entry-level position. Therefore, we prioritize positions first and then experience level within those positions.


4. **World Knowledge Consideration**: Typical career paths and progression in the tech industry play a significant role. For instance, an intern is typically at an entry level and doesn't overlap with senior levels, whereas a Manager usually corresponds to senior level roles.


Here is the semantic sorting of the combined values:


1. **Intern (Entry Level)**: "Intern" is typically the starting point in a tech career and is inherently entry level.
2. **Junior Developer (Entry Level)**: The next step after an intern, often still considered entry level.
3. **Junior Developer (Mid Level)**: As a Junior Developer gains experience, they move towards mid-level but still remain in the "junior" category.
4. **Senior Developer (Mid Level)**: Individuals in this role have significant experience but are not yet in leadership roles.
5. **Senior Developer (Senior Level)**: A highly experienced developer who is not necessarily in a leadership position but has deep technical expertise.
6. **Team Lead (Mid Level)**: Typically someone who leads a small team but not at the managerial level yet.
7. **Team Lead (Senior Level)**: A highly experienced team leader, potentially overseeing larger or more complex teams.
8. **Manager (Mid Level)**: A mid-level managerial role, overseeing teams or projects but not at the highest strategic level.
9. **Manager (Senior Level)**: A senior manager with extensive experience, overseeing larger departments or multiple teams.


To summarize, the sorting criteria prioritize the typical career ladder positions first and then within those positions, sort by experience level. This ensures a logical and understandable progression reflecting real-world career paths in the tech industry.

In [ ]:
prod_stock = semantic_sort_multiple_column("Product Category", "Electronics, Furniture, Clothing, Toys", "Stock Status", "In Stock, Out of Stock, Discontinued" )

In [ ]:
final_prod_stock = prod_stock.split("\n\n")
for suggestion in final_prod_stock:
  print(suggestion)
  print("\n")

To provide a semantic sorting of the combined values of the columns "Product Category" and "Stock Status," we need to consider the logical relationships and practical implications of these values. Here's a sorted list along with the rationale behind the ordering:


1. **Electronics - In Stock**
2. **Electronics - Out of Stock**
3. **Electronics - Discontinued**
4. **Furniture - In Stock**
5. **Furniture - Out of Stock**
6. **Furniture - Discontinued**
7. **Clothing - In Stock**
8. **Clothing - Out of Stock**
9. **Clothing - Discontinued**
10. **Toys - In Stock**
11. **Toys - Out of Stock**
12. **Toys - Discontinued**


### Sorting Criteria & Rationale:


1. **Product Category Priority:**
   - **Electronics**: Generally, electronics are high-value items with significant consumer interest and rapid technological advancements, making their stock status particularly crucial.
   - **Furniture**: Furniture is often a major purchase decision and can have logistical considerations, making its availability important.
   - **Clothing**: Clothing is a high-turnover category with seasonal influences, so its stock status is essential for fashion trends.
   - **Toys**: Toys are often seasonal (e.g., holidays) and trends can change quickly, but they are typically lower in value compared to the other categories.


2. **Stock Status Hierarchy:**
   - **In Stock**: Items that are currently available for purchase are of primary interest to consumers and businesses.
   - **Out of Stock**: Items that are temporarily unavailable but expected to be restocked soon are next in priority.
   - **Discontinued**: Items that are no longer available and will not be restocked are of the least immediate interest but still relevant for inventory and historical data.


### World Knowledge Considered:
- **Consumer Demand**: Electronics often have higher demand due to rapid technological advancements and higher price points.
- **Purchase Frequency**: Clothing and toys have higher turnover rates and seasonal demand.
- **Logistics and Availability**: Furniture involves logistical considerations like delivery and setup, making its availability important for planning.
- **Market Trends**: The rapidly changing nature of fashion and technology influences the prioritization of stock status in these categories.


This semantic sorting aims to prioritize items based on their perceived importance to consumers and businesses, ensuring that the most relevant and actionable information is presented first.

In [ ]:
course_diff = semantic_sort_multiple_column("Course Level", "Undergraduate, Graduate, Postgraduate", "Course Difficulty", "Beginner, Intermediate, Advanced")

In [ ]:
final_course_diff = course_diff.split("\n\n")
for suggestion in final_course_diff:
  print(suggestion)
  print("\n")

To provide a semantic sorting of the combined values from the columns "Course Level" and "Course Difficulty," we should consider both the hierarchical order of the course levels and the progressive nature of course difficulty.


### Course Level Hierarchy:
1. Undergraduate
2. Graduate
3. Postgraduate


### Course Difficulty Hierarchy:
1. Beginner
2. Intermediate
3. Advanced


### Combined Semantic Sorting Criteria:
1. **Primary Criterion: Course Level** - The course level represents a progression in academic study, with Undergraduate being the entry-level, followed by Graduate, and then Postgraduate. The higher the level, the more advanced the study.
2. **Secondary Criterion: Course Difficulty** - Within each course level, the difficulty indicates the complexity and depth of the course content, starting from Beginner to Advanced.


### Rationale:
- **Undergraduate** courses generally form the foundation of higher education and target a broader audience, often starting with basic concepts (Beginner) and progressing to more specialized topics (Intermediate, Advanced).
- **Graduate** courses are more specialized and build upon the knowledge gained at the undergraduate level, typically requiring more in-depth study and analysis.
- **Postgraduate** courses are the most advanced, focusing on specialized and research-oriented topics that require a significant academic background.


### World Knowledge Considered:
- Educational systems typically structure learning in progressive stages, where each subsequent level builds on the previous one.
- Within each educational stage, courses often begin with introductory material and gradually increase in complexity.


### Sorted Combined Values:
Based on the above criteria, the combined values would be sorted as follows:


1. Undergraduate Beginner
2. Undergraduate Intermediate
3. Undergraduate Advanced
4. Graduate Beginner
5. Graduate Intermediate
6. Graduate Advanced
7. Postgraduate Beginner
8. Postgraduate Intermediate
9. Postgraduate Advanced


This sorting ensures that the foundational undergraduate courses appear first, progressing through difficulty levels within each educational stage, followed by the more specialized graduate and then the most advanced postgraduate courses.

Testing functions for report

In [5]:
def determine_semantic_sortable_columns(df, mod='4o'):
    F'''
        DETERMINE WHICH COLUMNS CAN BE USED TO SEMANTICALLY SORT THE DATASET -> OUTPUTS LIST [] OF COLUMNS
'''
    column_names = df.columns.tolist()
    column_values = {col: df[col].unique().tolist() for col in column_names}
    column_info = "\n".join([f"{col}: {values}" for col, values in column_values.items()])

    # prompt = f"""
    # Given a dataset with the following columns and their unique values: {column_info}, analyze and determine which columns can be semantically sorted. Semantic sorting refers to sorting columns based on the inherent meaning or contextual relationships of their values, rather than simple alphabetical or numerical order. For each column, evaluate whether its values have a natural hierarchy, contextual order, or categorical meaning or if any world knowledge can be used to sort the values of the columns. Remember, there can be multiple criterias to sort the values, even if one is present, suggest that. Examples of suitable columns include those with job levels (e.g., 'Junior', 'Mid', 'Senior'), geographic locations (e.g., 'North America', 'Europe', 'Asia'), or time-related values (e.g., 'Morning', 'Afternoon', 'Evening'). Additionally, exclude columns that contain unique identifiers, such as names, IDs, or any other primary key values that do not lend themselves to semantic ordering. Lastly, provide a list of the columns that are most suitable for semantic sorting, enclosed in square brackets, based on this analysis.
    # """'

    prompt_to_sort_values = f"Sort the values 'values' based on their semantic meaning for the column ''column_name'. Try to avoid alphabetical sorting and use context and semantic relationships. Provide the values and explain the sorting criteria. Give the best possible and most relevant criteria to sort the value and provide the full explanation of the sorting criteria for sure. Add 2 lines after every suggestion in the output."


    prompt = f"""
    Given a dataset with the following columns and their unique values: {column_info}, analyze and determine which columns can be semantically sorted. Semantic sorting refers to sorting columns based on the inherent meaning or contextual relationships of their values, rather than simple alphabetical or numerical order. For each column, evaluate whether its values have a natural hierarchy, contextual order, or categorical meaning or if any world knowledge can be used to sort the values of the columns. Remember, there can be multiple criterias to sort the values, even if one is present, suggest that. Examples of suitable columns include those with job levels (e.g., 'Junior', 'Mid', 'Senior'), geographic locations (e.g., 'North America', 'Europe', 'Asia'), or time-related values (e.g., 'Morning', 'Afternoon', 'Evening'). Additionally, exclude columns that contain unique identifiers, such as names, IDs, or any other primary key values that do not lend themselves to semantic ordering. Lastly, provide a list of the columns that are most suitable for semantic sorting, enclosed in square brackets, based on this analysis.
Consider world knowledge about the column and its values, which values are considered superior and which inferiro and provide suggestions. Give all the suggestions possible, even if there is not a universally accepted sorting order but consider the world knowledge about the column values, thier importance, how they are perceived, etc.
Refer this prompt I use to semantically sort a column given its values: ${prompt_to_sort_values}, and consider this and give the results. Try to ignore numerical columns or columns which contain dates.
After analyzing the columns, on the last line provide a list of the columns that are most suitable for semantic sorting, enclosed in square brackets [ ]. Give only the list on that line, nothing else
"""
    response = openai.ChatCompletion.create(
        model=f"gpt-{mod}",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=1000,
        n=1,
        stop=None,
        temperature=0.7
    )

    result = response.choices[0].message['content']
    return result